const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {Worker,isMainThread,workerData,parentPort}=require('node:worker_threads');
const E=require('./bio-engine'),base=path.join(__dirname,'balance-results'),dir=path.join(__dirname,'balance-v4-results');
const old=JSON.parse(fs.readFileSync(path.join(base,'summary.json'),'utf8'));
function run(job){let s=E.initial(job.seed);s.bio.factions={black:job.black,white:job.white};const actions=[],depths={};let status='limit',error=null;const started=Date.now();try{for(let step=0;step<400&&!s.over;step++){const ai=E.choose(s,6);depths[ai.depth]=(depths[ai.depth]||0)+1;const r=ai.point===null?E.pass(s):E.play(s,ai.point);if(r.error){status='blocked';error=r.error;break;}actions.push({action:ai.point,depth:ai.depth,nodes:ai.nodes,event:r.event});s=r.state;}if(s.over)status='completed';if(s.over&&s.board.some((p,i)=>p&&p.kind!=='spore'&&!E.libs(s.board,E.group(s.board,i)).length)){status='invalid';error='zero-liberty terminal';}}catch(e){status='exception';error=e.stack;}let score=null;try{const a=E.score(s);score={black:a.black,white:a.white,neutral:a.neutral};}catch(e){error=(error||'')+e.message;}
 const row={id:job.id,black:job.black,white:job.white,seed:job.seed,status,winner:s.over?s.winner:null,error,reason:s.reason,score,ply:s.ply,actionCount:actions.length,elapsedMs:Date.now()-started,depths,previousStatus:job.status,previousWinner:job.winner};fs.writeFileSync(path.join(dir,'game-'+String(job.id).padStart(3,'0')+'.json'),JSON.stringify({row,actions,finalState:s},null,2));return row;
}
if(!isMainThread){const rows=[];for(const job of workerData.jobs){rows.push(run(job));if(rows.length%10===0)parentPort.postMessage({progress:rows.length,total:workerData.jobs.length,pair:workerData.pair});}parentPort.postMessage({done:rows});}
else{fs.mkdirSync(dir,{recursive:true});const pairs=[['virus','bacteria'],['virus','fungi'],['bacteria','fungi']];const hashes=Object.fromEntries(['bio-engine.js','parity-engine.js','bio-features.js','parity-app.js'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,f))).digest('hex')]));
 Promise.all(pairs.map(pair=>new Promise((resolve,reject)=>{const jobs=Array.from({length:100},(_,i)=>({id:pairs.indexOf(pair)*100+i+1,seed:crypto.createHash('sha256').update('bio-balance-v4:'+Math.floor(i/2)).digest().readUInt32LE(0)||1,black:pair[i%2],white:pair[1-i%2]})),w=new Worker(__filename,{workerData:{jobs,pair}});w.on('message',m=>{if(m.done)resolve(m.done);else console.log(JSON.stringify(m));});w.on('error',reject);w.on('exit',code=>{if(code)reject(Error('worker exit '+code));});}))).then(arr=>{const results=arr.flat().sort((a,b)=>a.id-b.id);const summary=pairs.map(pair=>{const rows=results.filter(r=>pair.includes(r.black)&&pair.includes(r.white)),complete=rows.filter(r=>r.status==='completed');const wins=f=>complete.filter(r=>r.winner!=='draw'&&r[r.winner]===f).length;return {pair,attempted:rows.length,completed:complete.length,winsA:wins(pair[0]),winsB:wins(pair[1]),draws:complete.filter(r=>r.winner==='draw').length,failed:rows.filter(r=>r.status!=='completed'),byBlack:pair.map(f=>{const x=complete.filter(r=>r.black===f);return {black:f,n:x.length,blackWins:x.filter(r=>r.winner==='black').length,whiteWins:x.filter(r=>r.winner==='white').length,draws:x.filter(r=>r.winner==='draw').length};})};});fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify({date:new Date().toISOString(),level:6,hashes,policy:'100 per pair: 50 SHA256 bio-balance-v4 seeds with swapped colors; current level 6 normal and migration search, deterministic 2400-node cap, iterative depth <=4, ranked beam width 5. No first-choice migration override.',summary,results},null,2));fs.writeFileSync(path.join(dir,'games.csv'),'\ufeff'+['id,black,white,seed,status,winner,blackScore,whiteScore,ply,actions,previousStatus,previousWinner',...results.map(r=>[r.id,r.black,r.white,r.seed,r.status,r.winner,r.score?.black,r.score?.white,r.ply,r.actionCount,r.previousStatus,r.previousWinner].join(','))].join('\n'));console.log(JSON.stringify(summary,null,2));}).catch(e=>{console.error(e);process.exitCode=1;});}
