/* Read-only game audit: uses the current level-6 engine and UI migration policy. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const E=require('./bio-engine.js');
const dir=path.join(__dirname,'balance-results');fs.mkdirSync(dir,{recursive:true});
const sources=['bio-engine.js','bio-features.js','parity-engine.js','parity-app.js'];
const hashes=Object.fromEntries(sources.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,f))).digest('hex')]));
const html=fs.readFileSync(path.join(__dirname,'biogo.html'),'utf8');
const inline=html.match(/<script id="parity-engine">([\s\S]*?)<\/script>/)[1];
const expected=['parity-engine.js','bio-features.js','bio-engine.js'].map(f=>fs.readFileSync(path.join(__dirname,f),'utf8').trim()).join('\n');
if(inline.trim().replace(/\r\n/g,'\n')!==expected.replace(/\r\n/g,'\n'))throw Error('Inline worker engine differs from local engine');
const results=process.argv.includes('--resume')?JSON.parse(fs.readFileSync(path.join(dir,'summary.json'),'utf8')).results:[],pairs=[['virus','bacteria'],['virus','fungi'],['bacteria','fungi']];
function seedFor(i){return crypto.createHash('sha256').update('bio-balance-v1:'+i).digest().readUInt32LE(0)||1;}
function game(black,white,seed){let s=E.initial(seed);s.bio.factions={black,white};const actions=[],started=Date.now();let status='limit',error=null;try{for(let i=0;i<400;i++){if(s.over){status='completed';break;}const choice=s.phase==='migration'&&s.pending?.choices?.length?{point:s.pending.choices[0]}:E.choose(s,6).point;const r=choice===null?E.pass(s):E.play(s,choice);if(r.error){status='blocked';error=r.error;break;}actions.push({action:choice,event:JSON.parse(JSON.stringify(r.event)),ply:r.state.ply,phase:r.state.phase});s=r.state;}if(s.over)status='completed';}catch(e){status='exception';error=e.message;}let score;try{score=E.score(s);}catch(e){error=(error||'')+'; score: '+e.message;}
 const row={id:results.length+1,black,white,seed,status,error,winner:s.over?s.winner:null,reason:s.reason,score:score?{black:score.black,white:score.white,neutral:score.neutral}:null,ply:s.ply,actionCount:actions.length,phase:s.phase,remainingChoices:s.pending?.choices?.length,remainingVictims:s.pending?s.pending.captured.length-s.pending.cursor:0,elapsedMs:Date.now()-started};
 fs.writeFileSync(path.join(dir,'game-'+String(row.id).padStart(3,'0')+'.json'),JSON.stringify({row,actions,finalState:s},null,2));results.push(row);return row;
}
for(const [a,b]of pairs){const prior=results.filter(r=>[a,b].includes(r.black)&&[a,b].includes(r.white));let complete=[a,b].map(f=>prior.filter(r=>r.black===f&&r.status==='completed').length),attempts=prior.length;for(let i=prior.length/2;i<300&&(i<25||complete.some(n=>n<25));i++){const seed=seedFor(i);for(let reverse=0;reverse<2;reverse++){const row=game(reverse?b:a,reverse?a:b,seed);attempts++;if(row.status==='completed')complete[reverse]++;}if(i%5===4)console.log(JSON.stringify({pair:[a,b],attempts,completed:complete}));}console.log('PAIR DONE '+JSON.stringify({pair:[a,b],attempts,complete}));}
const summary=pairs.map(([a,b])=>{const games=results.filter(r=>[a,b].includes(r.black)&&[a,b].includes(r.white)),ok=games.filter(r=>r.status==='completed');const wins=f=>ok.filter(r=>r.winner!=='draw'&&r[r.winner]===f).length;return {pair:[a,b],attempted:games.length,completed:ok.length,winsA:wins(a),winsB:wins(b),draws:ok.filter(r=>r.winner==='draw').length,blocked:games.filter(r=>r.status!=='completed').length,byBlack:[a,b].map(f=>{const g=ok.filter(r=>r.black===f);return {black:f,n:g.length,blackWins:g.filter(r=>r.winner==='black').length,whiteWins:g.filter(r=>r.winner==='white').length,draws:g.filter(r=>r.winner==='draw').length};}),errors:games.filter(r=>r.status!=='completed').reduce((m,r)=>(m[r.error||r.status]=(m[r.error||r.status]||0)+1,m),{})};});
fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify({date:new Date().toISOString(),level:6,policy:'Normal: E.choose(s,6). Migration: first choice, matching UI. 25 paired seeds minimum; additional pairs until >=25 completed per color or 300 paired seeds.',hashes,summary,results},null,2));
fs.writeFileSync(path.join(dir,'games.csv'),'\ufeff'+['id,black,white,seed,status,winner,blackScore,whiteScore,ply,actions,error',...results.map(r=>[r.id,r.black,r.white,r.seed,r.status,r.winner,r.score?.black,r.score?.white,r.ply,r.actionCount,JSON.stringify(r.error||'')].join(','))].join('\n'));
console.log(JSON.stringify(summary,null,2));
