/* Integration of the supplied BioFeatures module with the unchanged ParityEngine. */
(function(root,factory){const api=typeof module==='object'&&module.exports?factory(require('./parity-engine.js'),require('./bio-features.js'),root):factory(root.ParityEngine,root.BioFeatures,root);if(typeof module==='object'&&module.exports)module.exports=api;root.BioEngine=api;if(typeof window!=='undefined'||typeof importScripts==='function')root.ParityEngine=api;})(globalThis,function(P,B,root){
'use strict';
const cp=P.copy,adj=P.adj,xy=i=>[Math.floor(i/6),i%6],idx=p=>p[0]*6+p[1],alive=p=>p&&p.kind!=='spore',colors=['black','white'],factions=['virus','bacteria','fungi'],MAX_HEALTH=36;
const stock={virus:{1:2,2:2,3:6,4:4},bacteria:{1:0,2:2,3:10,4:0},fungi:{1:0,2:2,3:8,4:0}};
function occupancy(s){return colors.reduce((out,color)=>{out[color]=s.board.filter(p=>alive(p)&&p.color===color).length;return out;},{});}
function initHealth(s){s.bio.health={black:MAX_HEALTH,white:MAX_HEALTH};s.bio.healthOccupancy=occupancy(s);}
function applyHealth(s,e){const health=score(s).health;s.bio.health=health;s.bio.healthOccupancy=occupancy(s);if(e)e.details.push('生命值结算：敌方控制点造成伤害，被提后自动恢复');return health;}
function initial(seed,options={}){const s=P.initial(seed);if(options.mode===false||(options.mode===undefined&&root.BIO_MODE_DEFAULT===false)){s.bioMode=false;return s;}s.bioMode=true;s.bio=B.createInitialBioState(colors);s.bio.stock={black:cp(stock),white:cp(stock)};s.bio.round=0;s.bio.nextId=1;s.bio.dead=[];initHealth(s);s.phase='place';s.seen=[hash(s)];return s;}
const meta=(s,i)=>s.bio?.stoneMeta[s.board[i]?.id];
function boardAPI(s){return {getStoneAt:p=>alive(s.board[idx(p)])?meta(s,idx(p)):null,getOrthogonalNeighbors:p=>adj[idx(p)].map(xy),getAllNeighbors:p=>{const [r,c]=p,out=[];for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if((a||b)&&r+a>=0&&r+a<6&&c+b>=0&&c+b<6)out.push([r+a,c+b]);return out;}};}
function group(b,i){return alive(b[i])?P.group(b,i):[];}
function hash(s){return !s.bioMode?P.hash(s):JSON.stringify([s.board,s.turn,s.phase,s.locks,s.bio]);}
function rng(s){let x=s.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.seed=x>>>0;return s.seed/4294967296;}
function bacterialGroup(s,i){if(meta(s,i)?.faction!=='bacteria')return [];const q=[i],seen=new Set(q);for(let n=0;n<q.length;n++)for(const j of adj[q[n]])if(alive(s.board[j])&&s.board[j].color===s.board[i].color&&meta(s,j)?.faction==='bacteria'&&!seen.has(j)){seen.add(j);q.push(j);}return q;}
function effective(s,g,attacker){const raw=P.libs(s.board,g).length;let metas=g.map(i=>meta(s,i));const film=g.some(i=>bacterialGroup(s,i).length>=2);let n=B.effectiveLibertyCount(raw,metas,attacker);if(film&&!metas.every(m=>m.faction==='bacteria'))n+=B.CONFIG.BIOFILM_LIBERTY_BONUS;return n;}
function score(s){if(!s.bioMode)return P.score(s);const a={black:0,white:0,neutral:0,infectedArea:0,owners:Array(36).fill(null),stones:{black:0,white:0},territory:{black:0,white:0},factions:{black:{virus:0,bacteria:0,fungi:0},white:{virus:0,bacteria:0,fungi:0}},maxHealth:MAX_HEALTH},hasBoth=colors.every(c=>s.board.some(p=>alive(p)&&p.color===c));const seen=new Set();for(let i=0;i<36;i++){const p=s.board[i];if(p?.kind==='spore'){a.neutral++;a.infectedArea++;continue;}if(p){a[p.color]++;a.stones[p.color]++;a.owners[i]=p.color;a.factions[p.color][meta(s,i).faction]++;continue;}if(seen.has(i))continue;const q=[i],edges=new Set();seen.add(i);for(let n=0;n<q.length;n++)for(const j of adj[q[n]]){const z=s.board[j];if(z){if(alive(z))edges.add(z.color);}else if(!seen.has(j)){seen.add(j);q.push(j);}}if(edges.size===1&&hasBoth){const c=[...edges][0];a[c]+=q.length;a.territory[c]+=q.length;q.forEach(j=>a.owners[j]=c);}else a.neutral+=q.length;}a.health={black:MAX_HEALTH-a.white,white:MAX_HEALTH-a.black};return a;}
function finish(s,reason,winner){if(s.bio?.simple)simpleSettleZeroLiberties(s,{removed:0,details:[]});const a=score(s),hp=a.health;s.over=true;s.phase='finished';s.reason=reason;s.winner=winner||(hp.black===hp.white?'draw':hp.black>hp.white?'black':'white');return s;}
function event(color,kind,point=null){return {color,kind,point,captured:0,destinations:[],removed:0,details:[]};}
function convert(s,e){for(const m of Object.values(s.bio.stoneMeta))if(m.state===B.STATE.INFECTED){m.faction='virus';m.state=B.STATE.ACTIVE;e.details.push('感染达到阈值：一枚棋子归化为病毒，黑白不变');}}
function tick(s,e){s.bio.round++;for(const m of Object.values(s.bio.sporeMarkers))if(m.createdRound===s.bio.round-1)m.turnsElapsed--;const changed=B.tickSporeTimers(s.bio,boardAPI(s));for(const c of changed){const i=idx(c.pos),m=s.bio.stoneMeta[c.key];if(c.result==='REVIVED'){s.board[i]={id:c.key,color:c.color,migrated:false};if(!P.libs(s.board,group(s.board,i)).length){s.board[i]={kind:'spore',id:c.key,color:null,migrated:false,dead:true};m.state=B.STATE.SPORE;s.bio.dead.push(c.key);e.details.push(P.coord(i)+' 无气，复苏失败');}else e.details.push(P.coord(i)+' 孢子复苏');}else{s.board[i].dead=true;s.bio.dead.push(c.key);e.details.push(P.coord(i)+' 变为永久死点');}}for(const [id,m]of Object.entries(s.bio.sporeMarkers))s.bio.stoneMeta[id].sporeTimer=Math.max(0,3-m.turnsElapsed);}
function endTurn(s,e){s.ply++;s.last=s.last??null;const actor=s.turn;s.turn=P.other(actor);s.phase='place';if(actor==='white')tick(s,e);const hp=applyHealth(s,e);s.seen.push(hash(s));if(!s.over&&(hp.black===0||hp.white===0))finish(s,hp.black===hp.white?'双方生命值归零':hp.black===0?'黑方生命值归零':'白方生命值归零',hp.black===hp.white?'draw':hp.black===0?'white':'black');else adjudicate(s);return {state:s,event:e};}
function bonusActions(s){if(!s.bioMode||s.phase!=='bonus')return [];const out=[],vis=new Set();for(let i=0;i<36;i++)if(alive(s.board[i])&&s.board[i].color===s.turn&&meta(s,i).faction==='bacteria'){
 const g=bacterialGroup(s,i);if(!vis.has(i)){g.forEach(j=>vis.add(j));const libs=P.libs(s.board,g);if(libs.length>=3&&s.bio.vp[s.turn]>=1&&g.every(j=>(meta(s,j).divisionReady||0)<=s.bio.round))for(const p of libs)if(!s.locks[s.turn].includes(p))out.push({type:'divide',source:i,point:p});}
 if(s.bio.vp[s.turn]>=1)for(const j of adj[i])if(s.board[j]?.kind==='spore'&&!s.board[j].dead&&s.bio.sporeMarkers[s.board[j].id]&&!s.bio.sporeMarkers[s.board[j].id].interfered&&s.bio.sporeMarkers[s.board[j].id].color!==s.turn)out.push({type:'interfere',source:i,point:j});
 }return out;}
function afterCapture(s,e){const p=s.pending;if(p){for(const g of p.groups){const records=g.map(k=>p.captured.find(x=>x.origin===k));const summary=B.resolveCaptureAftermath(s.bio,boardAPI(s),{capturedStones:records.map(x=>({key:x.stone.id,pos:xy(x.origin),migratedTo:x.dest===undefined?null:xy(x.dest)})),capturingFaction:p.faction,capturingPlayer:p.actor},()=>rng(s));if(summary.vpRefunded)e.details.push('提子返还 '+summary.vpRefunded+' VP');if(summary.infections.length)e.details.push(summary.infections.length+' 枚棋子将于下一次结算归化');}for(const x of p.captured)if(x.dest===undefined&&s.bio.stoneMeta[x.stone.id]?.state!==B.STATE.SPORE)delete s.bio.stoneMeta[x.stone.id];for(const x of p.captured)if(s.bio.sporeMarkers[x.stone.id])s.bio.sporeMarkers[x.stone.id].createdRound=s.bio.round;s.turn=p.actor;delete s.pending;}s.phase='bonus';if(!bonusActions(s).length)return endTurn(s,e);return {state:s,event:e};}
function migrate(s,e,choice){const p=s.pending;while(p.cursor<p.captured.length){const x=p.captured[p.cursor],m=s.bio.stoneMeta[x.stone.id];if(m.faction==='fungi'){p.cursor++;continue;}const available=p.pool.filter(i=>!s.board[i]).filter(i=>{s.board[i]={...x.stone,migrated:true};const ok=[...p.destinations,i].every(j=>P.libs(s.board,group(s.board,j)).length>0);s.board[i]=null;return ok;});if(!available.length){p.cursor++;e.removed++;continue;}const distance=i=>Math.min(...p.captured.map(t=>Math.abs(xy(t.origin)[0]-xy(i)[0])+Math.abs(xy(t.origin)[1]-xy(i)[1]))),min=Math.min(...available.map(distance)),ties=available.filter(i=>distance(i)===min);
 if(m.faction==='virus'&&ties.length>1&&choice===undefined){p.choices=ties;s.phase='migration';s.turn=m.color;e.details.push('病毒方选择等距迁移点');return {state:s,event:e};}
 let dest;if(m.faction==='virus'&&ties.length>1){if(!ties.includes(choice))return {error:'请选择高亮的等距迁移点。'};dest=B.pickMigrationTarget(m,ties,()=>rng(s),()=>choice);choice=undefined;}else dest=B.pickMigrationTarget(m,ties,()=>rng(s));s.board[dest]={...x.stone,migrated:true};x.dest=dest;p.destinations.push(dest);e.destinations.push(dest);p.cursor++;delete p.choices;
 }return afterCapture(s,e);}
function capture(s,point,faction,e){const actor=s.turn,groups=[],seen=new Set();for(const j of adj[point])if(alive(s.board[j])&&s.board[j].color===P.other(actor)&&!seen.has(j)){const g=group(s.board,j);g.forEach(k=>seen.add(k));if(effective(s,g,faction)<=0)groups.push(g);else if(P.libs(s.board,g).length===0){B.onFailedCaptureAttempt(s.bio,g.map(k=>s.board[k].id));e.details.push('生物膜阻止提子，耐药计数增加');}}
 if(!groups.length){if(!P.libs(s.board,group(s.board,point)).length)return {error:'落子后无真实气，不能自杀。'};return afterCapture(s,e);}
 const captured=groups.flat().map(i=>({origin:i,stone:s.board[i]}));for(const x of captured){s.locks[x.stone.color]=[...new Set([...s.locks[x.stone.color],x.origin])].sort((a,b)=>a-b);s.board[x.origin]=null;}for(const x of captured)if(s.bio.stoneMeta[x.stone.id].faction==='fungi'){const m=s.bio.stoneMeta[x.stone.id];m.state=B.STATE.SPORE;m.sporeTimer=3;s.board[x.origin]={kind:'spore',id:x.stone.id,color:null,migrated:false};s.bio.sporeMarkers[x.stone.id]={originOwner:m.color,color:m.color,pos:xy(x.origin),turnsElapsed:0,interfered:false};e.details.push(P.coord(x.origin)+' 原地孢子化');}
 if(!P.libs(s.board,group(s.board,point)).length)return {error:'提子后仍无气，不能落子。'};
 const pool=[...new Set(s.board.flatMap((p,i)=>alive(p)&&p.color===actor?P.libs(s.board,[i]):[]))].filter(i=>!captured.some(x=>x.origin===i));s.pending={actor,faction,groups,captured,pool,cursor:0,destinations:[]};e.captured=captured.length;return migrate(s,e);}
function play(source,action,options={}){
 if(!source.bioMode)return P.play(source,typeof action==='object'?action.point:action,options);
 if(source.over)return {error:'对局已结束'};const s=cp(source);let a=typeof action==='number'?{point:action,faction:'virus',tier:4}:action;if(!a)return pass(source);const e=event(s.turn,a.type||'place',a.point??null);
 if(s.phase==='migration'){e.kind='migration';return migrate(s,e,a.point);}
 if(s.phase==='bonus'){
  if(a.type==='end')return endTurn(s,e);const available=bonusActions(s).find(x=>x.type===a.type&&x.source===a.source&&x.point===a.point);if(!available)return {error:'技能条件不满足或处于冷却中。'};
  if(a.type==='interfere'){B.attemptAntifungalInterference(s.bio,s.turn,s.board[a.point].id);e.details.push(P.coord(a.point)+' 孢子受到干扰，不能复苏');return {state:s,event:e};}
  const g=bacterialGroup(s,a.source),ready=s.bio.round+2;const sourceMeta=meta(s,a.source),id='b'+s.bio.nextId++;const arr=g.map(i=>meta(s,i));arr.liberties=[a.point];arr.liberties=P.libs(s.board,g);const result=B.attemptDivision(s.bio,s.turn,arr,g.map(i=>s.board[i].id).sort().join(':'),s.bio.round,()=>arr.liberties.indexOf(a.point)/arr.liberties.length);if(!result.ok)return {error:'无法分裂'};B.registerDivisionUsed(s.bio,g.map(i=>s.board[i].id).sort().join(':'),s.bio.round);s.bio.stoneMeta[id]=B.createStoneMeta('bacteria',sourceMeta.tier,s.turn);g.forEach(i=>meta(s,i).divisionReady=ready);s.bio.stoneMeta[id].divisionReady=ready;s.board[a.point]={id,color:s.turn,migrated:false};e.details.push('二分裂消耗 1 VP');return capture(s,a.point,'bacteria',e);
 }
 if(!Number.isInteger(a.point)||a.point<0||a.point>=36||s.board[a.point]||s.locks[s.turn].includes(a.point))return {error:'此处已占用、为孢子死点，或禁止该颜色回填。'};
 if(!factions.includes(a.faction)||![1,2,3,4].includes(+a.tier))return {error:'请选择派系和等级。'};
 if(!s.bio.stock[s.turn][a.faction][a.tier])return {error:'该派系等级的棋子储备已用完。'};convert(s,e);const v=B.validatePlacement(s.bio,boardAPI(s),s.turn,xy(a.point),s.turn,a.faction,+a.tier,{declareSporeSpread:!!a.spread});if(!v.ok)return {error:v.detail||v.reason};const id='b'+s.bio.nextId++;B.commitPlacement(s.bio,s.turn,id,xy(a.point),s.turn,a.faction,+a.tier,v);s.bio.stock[s.turn][a.faction][a.tier]--;s.board[a.point]={id,color:s.turn,migrated:false};s.last=a.point;s.passes=0;e.faction=a.faction;e.tier=a.tier;e.cost=v.cost;return capture(s,a.point,a.faction,e);
}
function pass(source){if(!source.bioMode)return P.pass(source);if(source.over)return {error:'对局已结束'};if(source.phase==='migration')return {error:'请先为病毒选择迁移点。'};if(source.phase==='bonus')return play(source,{type:'end'});const s=cp(source),e=event(s.turn,'pass');convert(s,e);s.passes++;s.last=null;const r=endTurn(s,e);if(s.passes>=2)finish(s,'双方连续停一手');return r;}
function placementOptions(s){const out=[];for(const f of factions)for(const t of [1,2,3,4])if(s.bio.stock[s.turn][f][t]>0&&s.bio.vp[s.turn]>=B.vpCostForTier(t))for(let i=0;i<36;i++)if(!s.board[i]&&!s.locks[s.turn].includes(i)){out.push({point:i,faction:f,tier:t});if(f==='fungi'&&s.bio.vp[s.turn]>=B.vpCostForTier(t)+2&&s.bio.sporeSpreadUsed[s.turn]<2)out.push({point:i,faction:f,tier:t,spread:true});}return out;}
function possible(s){return placementOptions(s).some(a=>!play(s,a,{probe:true}).error);}
let probing=0;
function adjudicate(s){if(!s.bioMode)return P.adjudicate(s);if(probing||s.phase!=='place'||s.over)return s;if(s.board.every(Boolean)&&!Object.keys(s.bio.sporeMarkers).length)return finish(s,'棋盘已满');if(Object.keys(s.bio.sporeMarkers).length)return s;probing++;try{if(!possible(s)&&!possible({...s,turn:P.other(s.turn)}))finish(s,'双方资源或落点不足，均无合法落子');}finally{probing--;}return s;}
function legal(s,color=s.turn){if(!s.bioMode)return P.legal(s,color);if(s.phase==='migration')return s.pending.choices;if(s.phase==='bonus')return [...new Set(bonusActions(s).map(a=>a.point))];probing++;try{return [...new Set(placementOptions({...s,turn:color}).filter(a=>!play({...s,turn:color},a).error).map(a=>a.point))];}finally{probing--;}}
function basic(s,i,color=s.turn){if(!s.bioMode)return P.basic(s,i,color);return legal(s,color).includes(i);}
function evaluate(s,color){if(!s.bioMode)return P.evaluate(s,color);if(s.over)return s.winner==='draw'?0:s.winner===color?100000:-100000;const a=score(s),op=P.other(color);let n=(a.stones[color]-a.stones[op])*35+(a.territory[color]-a.territory[op])*3+(s.bio.vp[color]-s.bio.vp[op])*5;for(let i=0;i<36;i++)if(alive(s.board[i]))n+=(s.board[i].color===color?1:-1)*(Math.min(P.libs(s.board,group(s.board,i)).length,4)*2+(meta(s,i).faction==='bacteria'&&bacterialGroup(s,i).length>1?10:0));return n;}
function choose(s,level=4,budget){
 if(!s.bioMode)return P.choose(s,level,budget);level=Math.max(1,Math.min(6,level));const deadline=Date.now()+(budget||[0,30,100,220,400,700,1100][level]),owner=s.turn;let nodes=0,depth=1;
 const actions=t=>t.phase==='migration'?t.pending.choices.map(point=>({point})):t.phase==='bonus'?[...bonusActions(t),{type:'end'}]:placementOptions(t);
 const rank=t=>{const out=[];for(const a of actions(t)){const r=play(t,a);if(r.error)continue;nodes++;out.push({a,s:r.state,v:evaluate(r.state,t.turn)});if(Date.now()>deadline&&out.length)break;}if(!out.length){const r=pass(t);if(!r.error)out.push({a:null,s:r.state,v:evaluate(r.state,t.turn)});}return out.sort((a,b)=>b.v-a.v);};
 const search=(t,d)=>{if(!d||t.over||Date.now()>deadline)return evaluate(t,owner);const children=rank(t).slice(0,level>=5?5:3);if(!children.length)return evaluate(t,owner);const values=children.map(c=>search(c.s,d-1));return t.turn===owner?Math.max(...values):Math.min(...values);};
 probing++;try{const ranked=rank(s);if(!ranked.length)return {point:null,nodes,depth};if(level===1)return {point:ranked[(s.seed>>>0)%ranked.length].a,nodes,depth};let best=ranked[0];if(level>=3){for(let d=2;d<=(level>=5?3:2);d++){let choice=best,value=-Infinity,complete=true;for(const r of ranked.slice(0,level>=5?8:5)){if(Date.now()>deadline){complete=false;break;}const v=search(r.s,d-1);if(v>value){value=v;choice=r;}}if(complete){best=choice;depth=d;}else break;}}return {point:best.a,nodes,depth};}finally{probing--;}
}
function valid(s){if(!s?.bioMode)return P.valid(s);try{return Array.isArray(s.board)&&s.board.length===36&&colors.includes(s.turn)&&['place','bonus','migration','finished'].includes(s.phase)&&colors.every(c=>Number.isFinite(s.bio.vp[c])&&s.bio.vp[c]>=0&&Number.isInteger(s.bio.health?.[c])&&s.bio.health[c]>=0&&s.bio.health[c]<=MAX_HEALTH&&Array.isArray(s.locks[c])&&s.locks[c].every(i=>Number.isInteger(i)&&i>=0&&i<36)&&factions.every(f=>[1,2,3,4].every(t=>Number.isInteger(s.bio.stock[c][f][t])&&s.bio.stock[c][f][t]>=0)))&&s.board.every(p=>!p||(s.bio.stoneMeta[p.id]&&factions.includes(s.bio.stoneMeta[p.id].faction)&&[1,2,3,4].includes(s.bio.stoneMeta[p.id].tier)&&(p.kind==='spore'||colors.includes(p.color))))&&Array.isArray(s.seen)&&Number.isInteger(s.seed)&&Number.isInteger(s.ply);}catch{return false;}}

// Simplified bio rules v0.2: parity-go core plus faction capture effects.
function simpleInitial(seed){const s=P.initial(seed);s.bioMode=true;s.bio=B.createInitialBioState(colors);s.bio.simple=true;s.bio.stock=null;s.bio.vp={black:0,white:0};s.bio.factions={black:null,white:null};s.bio.nextId=1;s.bio.dead=[];s.bio.noMoveTurns={black:0,white:0};initHealth(s);s.phase='place';s.seen=[hash(s)];return s;}
function simpleMeta(s,i){return s.bio?.stoneMeta[s.board[i]?.id];}
function simpleEvent(c,k,p=null){return {color:c,kind:k,point:p,captured:0,destinations:[],removed:0,details:[]};}
let simpleProbing=0;
function simpleCanPlay(s,color){for(const a of simplePlacementOptions({...s,turn:color}))if(!simplePlay({...s,turn:color},a).error)return true;return false;}
function simpleSettleZeroLiberties(s,e){
 const seen=new Set();let removed=0,changed=true;
 while(changed){changed=false;const doomed=[];
  for(let i=0;i<36;i++)if(alive(s.board[i])&&!seen.has(i)){
   const g=group(s.board,i);g.forEach(j=>seen.add(j));
   if(!P.libs(s.board,g).length)doomed.push(g);
  }
  if(!doomed.length)break;changed=true;seen.clear();
  for(const g of doomed)for(const i of g){const stone=s.board[i];if(!alive(stone))continue;
   s.locks[stone.color]=[...new Set([...(s.locks[stone.color]||[]),i])].sort((a,b)=>a-b);
   delete s.bio.stoneMeta[stone.id];s.board[i]=null;removed++;
  }
 }
 if(removed){e.removed=(e.removed||0)+removed;e.details.push('全局结算：清理 '+removed+' 枚零气棋子');}
 return removed;
}
function simpleAdjudicate(s){if(simpleProbing||s.over||s.phase!=='place')return s;if(s.board.every(Boolean))return finish(s,'棋盘已满');simpleProbing++;try{if(!simpleCanPlay(s,s.turn)&&!simpleCanPlay(s,P.other(s.turn)))finish(s,'双方均无合法落子');}finally{simpleProbing--;}return s;}
function simpleTrackNoMove(s,e){if(simpleProbing||s.over||s.phase!=='place')return;const waiting=s.turn,counts=s.bio.noMoveTurns||(s.bio.noMoveTurns={black:0,white:0});let playable=false;simpleProbing++;try{playable=simpleCanPlay(s,waiting);}finally{simpleProbing--;}if(playable){counts[waiting]=0;return;}counts[waiting]=(counts[waiting]||0)+1;e.details.push((waiting==='black'?'黑方':'白方')+'无合法落子（'+counts[waiting]+'/2）');if(counts[waiting]>=2)finish(s,(waiting==='black'?'黑方':'白方')+'连续两次轮到自己均无合法落子');}
function simpleEndTurn(s,e){simpleSettleZeroLiberties(s,e);const actor=s.turn;s.ply++;s.turn=P.other(actor);s.phase='place';s.passes=e.kind==='pass'?s.passes+1:0;const hp=applyHealth(s,e);if(!simpleProbing)s.seen.push(hash(s));if(hp.black===0||hp.white===0)finish(s,hp.black===hp.white?'双方生命值归零':hp.black===0?'黑方生命值归零':'白方生命值归零',hp.black===hp.white?'draw':hp.black===0?'white':'black');else if(s.passes>=2)finish(s,'双方连续停手');else{simpleAdjudicate(s);simpleTrackNoMove(s,e);}return {state:s,event:e};}
function simpleCandidates(s,actor,origins){const set=new Set();for(let i=0;i<36;i++)if(alive(s.board[i])&&s.board[i].color===actor)for(const j of adj[i])if(!s.board[j]&&!origins.includes(j))set.add(j);return [...set];}
function simpleCapture(s,point,faction,e){
 const actor=s.turn,opp=P.other(actor),groups=[],seen=new Set();
 for(const j of adj[point])if(alive(s.board[j])&&s.board[j].color===opp&&!seen.has(j)){const g=group(s.board,j);g.forEach(k=>seen.add(k));if(P.libs(s.board,g).length===0)groups.push(g);}
 if(!groups.length){if(!P.libs(s.board,group(s.board,point)).length)return {error:'落子后无气，不能自杀。'};return simpleEndTurn(s,e);}
 const victims=groups.flatMap(g=>g.map(i=>({origin:i,stone:s.board[i]}))),origins=victims.map(x=>x.origin);
 for(const x of victims){s.locks[opp]=[...new Set([...(s.locks[opp]||[]),x.origin])].sort((a,b)=>a-b);s.board[x.origin]=null;}
 const pending=[],actorGroup=group(s.board,point);
 for(const x of victims){const m=s.bio.stoneMeta[x.stone.id];m.captureCount=(m.captureCount||0)+1;
   if(m.captureCount>=3){delete s.bio.stoneMeta[x.stone.id];e.removed++;e.details.push(P.coord(x.origin)+' '+m.faction+'第3次被提，直接剔除');continue;}
   if(m.faction==='fungi'){pending.push(x);continue;}
   if(m.faction==='virus'){const targets=actorGroup.filter(i=>i!==point&&alive(s.board[i])&&s.board[i].color===actor).sort((a,b)=>Math.abs(xy(a)[0]-xy(x.origin)[0])+Math.abs(xy(a)[1]-xy(x.origin)[1])-Math.abs(xy(b)[0]-xy(x.origin)[0])-Math.abs(xy(b)[1]-xy(x.origin)[1]));if(targets.length){const dest=targets[0],old=s.board[dest];s.board[dest]={...x.stone,migrated:true};delete s.bio.stoneMeta[old.id];x.dest=dest;e.destinations.push(dest);e.details.push(P.coord(x.origin)+' 病毒替换 '+P.coord(dest));continue;}}
   if(m.faction==='bacteria'){pending.push(x);continue;}delete s.bio.stoneMeta[x.stone.id];e.removed++;
 }
 e.captured=victims.length;
 if(pending.length){const faction=s.bio.stoneMeta[pending[0].stone.id].faction;
 const anchors=faction==='bacteria'?s.board.map((p,i)=>alive(p)&&p.color===opp&&meta(s,i)?.faction==='bacteria'?i:-1).filter(i=>i>=0):[];
 s.pending={actor,groups,captured:pending,cursor:0,choices:[],event:e,faction,anchors};s.phase='migration';s.turn=opp;e.details.push((faction==='bacteria'?'细菌':'真菌')+'迁移请被提方指定落点');return settleFungi(s,e);}
 s.turn=actor;return simpleEndTurn(s,e);
}

function fungiChoices(s){const p=s.pending;if(!p||p.cursor>=p.captured.length)return [];const x=p.captured[p.cursor],isBacteria=metaForPending(s,p)==='bacteria',anchors=isBacteria?(p.anchors||[]):[];
 const origins=p.captured.map(v=>v.origin),pool=isBacteria?[...new Set(anchors.filter(i=>alive(s.board[i])&&s.board[i].color===x.stone.color&&meta(s,i)?.faction==='bacteria').flatMap(i=>adj[i]))].filter(i=>!s.board[i]&&!origins.includes(i)):simpleCandidates(s,p.actor,origins);
 return pool.filter(i=>{s.board[i]={...x.stone,migrated:true};const ok=[...anchors,...(p.destinations||[]),i].every(j=>P.libs(s.board,group(s.board,j)).length>0);s.board[i]=null;return ok;});}
function metaForPending(s,p){return p.faction||s.bio.stoneMeta[p.captured[p.cursor]?.stone.id]?.faction||'fungi';}
function settleFungi(s,e){const p=s.pending;p.choices=fungiChoices(s);if(p.cursor<p.captured.length&&p.choices.length){s.phase='migration';s.turn=p.captured[p.cursor].stone.color;return {state:s,event:e};}const remaining=p.captured.length-p.cursor;if(remaining){for(const x of p.captured.slice(p.cursor))delete s.bio.stoneMeta[x.stone.id];e.removed+=remaining;e.details.push('无可存活气孔，剩余 '+remaining+' 枚被提棋子剔除');}const actor=p.actor;delete s.pending;s.turn=actor;return simpleEndTurn(s,e);}

function simplePlay(source,action){
 if(!source.bioMode)return P.play(source,typeof action==='object'?action.point:action);
 if(source.over)return {error:'对局已结束'};const s=cp(source),a=typeof action==='number'?{point:action,faction:'virus'}:(action||null);if(!a)return simplePass(source);
 if(s.phase==='migration'){const p=s.pending,e=simpleEvent(s.turn,'migration',a.point??null);const choices=fungiChoices(s);if(!choices.length)return settleFungi(s,e);if(!Number.isInteger(a.point)||!choices.includes(a.point))return {error:'请选择有气的高亮迁移点。'};const x=p.captured[p.cursor++];s.board[a.point]={...x.stone,migrated:true};(p.destinations??=[]).push(a.point);e.destinations.push(a.point);return settleFungi(s,e);}
 const point=a.point;if(!Number.isInteger(point)||point<0||point>=36||s.board[point]||s.locks[s.turn].includes(point))return {error:'此处已占用、为孢子或当前颜色禁回填。'};const faction=factions.includes(a.faction)?a.faction:'virus';const chosen=s.bio.factions[s.turn],enemy=s.bio.factions[P.other(s.turn)];if(chosen&&chosen!==faction)return {error:'本局已确定派系，不能更换。'};if(!chosen&&enemy===faction)return {error:'双方派系必须不同，请选择另外一个派系。'};s.bio.factions[s.turn]=chosen||faction;const id='b'+s.bio.nextId++;s.bio.stoneMeta[id]=B.createStoneMeta(faction,1,s.turn);s.bio.stoneMeta[id].captureCount=0;s.board[point]={id,color:s.turn,migrated:false};s.last=point;const e=simpleEvent(s.turn,'place',point);e.faction=faction;return simpleCapture(s,point,faction,e);
}
function simplePass(source){if(!source.bioMode)return P.pass(source);if(source.phase==='migration'){const t=cp(source);if(fungiChoices(t).length)return {error:'请先选择迁移点。'};return settleFungi(t,simpleEvent(t.turn,'migration'));}const s=cp(source),e=simpleEvent(s.turn,'pass');return simpleEndTurn(s,e);}
function simplePlacementOptions(s){const own=s.bio.factions?.[s.turn],enemy=s.bio.factions?.[P.other(s.turn)];return [...Array(36).keys()].filter(i=>!s.board[i]&&!s.locks[s.turn].includes(i)).flatMap(i=>factions.filter(f=>(!own||f===own)&&f!==enemy).map(f=>({point:i,faction:f})));}
function simpleLegal(s,color=s.turn){if(!s.bioMode)return P.legal(s,color);if(s.phase==='migration')return s.pending.choices||[];const out=[];for(const a of simplePlacementOptions({...s,turn:color}))if(!simplePlay({...s,turn:color},a).error&&!out.includes(a.point))out.push(a.point);return out;}
function simpleValue(s,color){if(s.over)return s.winner==='draw'?0:s.winner===color?10000:-10000;const a=score(s),op=P.other(color);let v=30*(a.stones[color]-a.stones[op])+4*(a.territory[color]-a.territory[op]);const seen=new Set();for(let i=0;i<36;i++)if(alive(s.board[i])&&!seen.has(i)){const g=group(s.board,i);g.forEach(j=>seen.add(j));const l=P.libs(s.board,g).length;v+=(s.board[i].color===color?1:-1)*(l===0?-35*g.length:l===1?-12*g.length:Math.min(l,5)*2);}return v;}
function simpleChoose(s,level=4,budget){
 if(!s.bioMode)return P.choose(s,level,budget);if(s.over)return {point:null,nodes:0,depth:0};
 level=Math.max(1,Math.min(6,Math.trunc(level)||4));const maxDepth=[0,1,1,2,2,3,4][level],cap=[0,120,180,400,700,1200,2400][level],beam=[0,1,2,3,4,4,5][level];let nodes=0;const rootColor=s.turn;
 const tie=(t,a)=>{let x=(t.seed^Math.imul(t.ply+1,0x9e3779b9)^Math.imul((a?.point??37)+1,0x85ebca6b)^Math.imul(({virus:3,bacteria:5,fungi:7}[a?.faction]||11),0xc2b2ae35))>>>0;for(let i=0;i<36;i++){const p=t.board[i];if(!p)continue;const m=meta(t,i),code=(p.color==='black'?17:31)^({virus:43,bacteria:59,fungi:71}[m?.faction]||97);x^=Math.imul((i+1)*code,0x27d4eb2d);}x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;return x>>>0;};
 const children=t=>{const acts=t.phase==='migration'?fungiChoices(t).map(point=>({point})):simplePlacementOptions(t),out=[];for(const a of acts){if(nodes>=cap)break;nodes++;const r=simplePlay(t,a);if(!r.error)out.push({a,s:r.state,v:simpleValue(r.state,t.turn)});}if(!out.length){const r=simplePass(t);if(!r.error)out.push({a:null,s:r.state,v:simpleValue(r.state,t.turn)});}return out.sort((a,b)=>b.v-a.v||tie(t,a.a)-tie(t,b.a));};
 const visit=(t,d,alpha,beta)=>{if(!d||t.over)return simpleValue(t,rootColor);if(nodes>=cap)throw 'budget';const list=children(t).slice(0,beam),max=t.turn===rootColor;let v=max?-Infinity:Infinity;for(const c of list){const q=visit(c.s,d-1,alpha,beta);v=max?Math.max(v,q):Math.min(v,q);if(max)alpha=Math.max(alpha,v);else beta=Math.min(beta,v);if(beta<=alpha)break;}return Number.isFinite(v)?v:simpleValue(t,rootColor);};
 simpleProbing++;try{const t=cp(s);t.seen=[];const ranked=children(t);if(!ranked.length)return {point:null,nodes,depth:0};if(s.ply===0){const opening=ranked.slice(0,Math.min(12,ranked.length)).sort((a,b)=>tie(s,a.a)-tie(s,b.a));return {point:opening[(s.seed>>>0)%opening.length].a,nodes,depth:1,nodeBudget:cap};}if(level===1)return {point:ranked[(s.seed>>>0)%ranked.length].a,nodes,depth:1};
 let best=ranked[0],depth=1;const selectNear=(items,value,tolerance)=>items.filter(x=>x.value>=value-tolerance).sort((a,b)=>tie(s,a.c.a)-tie(s,b.c.a))[0].c;if(maxDepth===1){const value=ranked[0].v;best=selectNear(ranked.map(c=>({c,value:c.v})),value,s.ply<8?16:0);}for(let d=2;d<=maxDepth;d++){let value=-Infinity,scored=[];try{for(const c of ranked.slice(0,beam)){const v=visit(c.s,d-1,-Infinity,Infinity);scored.push({c,value:v});if(v>value)value=v;}best=selectNear(scored,value,s.ply<8?16:0);depth=d;}catch(e){if(e!=='budget')throw e;break;}}return {point:best.a,nodes,depth,nodeBudget:cap};
 }finally{simpleProbing--;}
}

function simpleValid(s){return !!(s&&s.bioMode&&s.bio?.simple&&Array.isArray(s.board)&&s.board.length===36&&colors.includes(s.turn)&&['place','migration','finished'].includes(s.phase)&&Array.isArray(s.seen)&&Number.isInteger(s.seed)&&Number.isInteger(s.ply)&&(!s.over||!s.board.some((p,i)=>alive(p)&&!P.libs(s.board,group(s.board,i)).length)));}
return {...P,initial:simpleInitial,play:simplePlay,pass:simplePass,score,finish,group,hash,legal:simpleLegal,basic:(s,i,c)=>simpleLegal(s,c).includes(i),evaluate,choose:simpleChoose,valid:(s)=>s?.bio?.simple?simpleValid(s):valid(s),adjudicate:simpleAdjudicate,bonusActions:()=>[],meta,effective,boardAPI,bacterialGroup};
});
