/* The biology layer supplies selectors, state badges and faction history to the inherited UI. */
(()=>{
const $=id=>document.getElementById(id),F={virus:'病毒',bacteria:'细菌',fungi:'真菌'},roman={1:'I',2:'II',3:'III',4:'IV'};
const icons={virus:'<style>.ring{fill:#FBEAF0;stroke:#993556;stroke-width:2}.icon{color:#993556}</style><circle class="ring" cx="48" cy="48" r="44"/><g class="icon" transform="translate(48,48) scale(1.4)"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="0" cy="0" r="12"/><line x1="12" y1="0" x2="18" y2="0"/><line x1="8.49" y1="8.49" x2="12.73" y2="12.73"/><line x1="0" y1="12" x2="0" y2="18"/><line x1="-8.49" y1="8.49" x2="-12.73" y2="12.73"/><line x1="-12" y1="0" x2="-18" y2="0"/><line x1="-8.49" y1="-8.49" x2="-12.73" y2="-12.73"/><line x1="0" y1="-12" x2="0" y2="-18"/><line x1="8.49" y1="-8.49" x2="12.73" y2="-12.73"/></g><g fill="currentColor" stroke="none"><circle cx="18" cy="0" r="2"/><circle cx="12.73" cy="12.73" r="2"/><circle cx="0" cy="18" r="2"/><circle cx="-12.73" cy="12.73" r="2"/><circle cx="-18" cy="0" r="2"/><circle cx="-12.73" cy="-12.73" r="2"/><circle cx="0" cy="-18" r="2"/><circle cx="12.73" cy="-12.73" r="2"/></g></g>',bacteria:'<style>.ring{fill:#EAF3DE;stroke:#3B6D11;stroke-width:2}.icon{color:#3B6D11}</style><circle class="ring" cx="48" cy="48" r="44"/><g class="icon" transform="translate(48,48) scale(1.4)"><rect x="-17" y="-9" width="34" height="18" rx="9" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><line x1="0" y1="-9" x2="0" y2="9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-dasharray="2,2.5"/></g>',fungi:'<style>.ring{fill:#E1F5EE;stroke:#0F6E56;stroke-width:2}.icon{color:#0F6E56}</style><circle class="ring" cx="48" cy="48" r="44"/><g class="icon" transform="translate(48,48) scale(1.4)"><path d="M-15,2 C-15,-13 15,-13 15,2 Z" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><rect x="-4" y="2" width="8" height="13" rx="3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><g stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="-11" y1="2" x2="-11" y2="5"/><line x1="-5.5" y1="2" x2="-5.5" y2="5"/><line x1="0" y1="2" x2="0" y2="5"/><line x1="5.5" y1="2" x2="5.5" y2="5"/><line x1="11" y1="2" x2="11" y2="5"/></g><g fill="currentColor" stroke="none"><circle cx="-11" cy="-19" r="1.6"/><circle cx="5" cy="-21" r="1.2"/><circle cx="13" cy="-15" r="1.8"/></g></g>'};
const lineIcons={virus:'<g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="24" cy="24" r="12"/><line x1="36" y1="24" x2="42" y2="24"/><line x1="32.49" y1="32.49" x2="36.73" y2="36.73"/><line x1="24" y1="36" x2="24" y2="42"/><line x1="15.51" y1="32.49" x2="11.27" y2="36.73"/><line x1="12" y1="24" x2="6" y2="24"/><line x1="15.51" y1="15.51" x2="11.27" y2="11.27"/><line x1="24" y1="12" x2="24" y2="6"/><line x1="32.49" y1="15.51" x2="36.73" y2="11.27"/></g><g fill="currentColor" stroke="none"><circle cx="42" cy="24" r="2"/><circle cx="36.73" cy="36.73" r="2"/><circle cx="24" cy="42" r="2"/><circle cx="11.27" cy="36.73" r="2"/><circle cx="6" cy="24" r="2"/><circle cx="11.27" cy="11.27" r="2"/><circle cx="24" cy="6" r="2"/><circle cx="36.73" cy="11.27" r="2"/></g>',bacteria:'<g transform="translate(24,24)"><rect x="-17" y="-9" width="34" height="18" rx="9" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><line x1="0" y1="-9" x2="0" y2="9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-dasharray="2,2.5"/></g>',fungi:'<g transform="translate(24,24)"><path d="M-15,2 C-15,-13 15,-13 15,2 Z" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><rect x="-4" y="2" width="8" height="13" rx="3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><g stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="-11" y1="2" x2="-11" y2="5"/><line x1="-5.5" y1="2" x2="-5.5" y2="5"/><line x1="0" y1="2" x2="0" y2="5"/><line x1="5.5" y1="2" x2="5.5" y2="5"/><line x1="11" y1="2" x2="11" y2="5"/></g><g fill="currentColor" stroke="none"><circle cx="-11" cy="-19" r="1.6"/><circle cx="5" cy="-21" r="1.2"/><circle cx="13" cy="-15" r="1.8"/></g></g>'};
const icon=f=>`<svg viewBox="0 0 48 48" fill="none" aria-hidden="true">${lineIcons[f]||''}</svg>`;
let selected={black:{faction:'virus',tier:4},white:{faction:'virus',tier:4}},ability=null,source=null;
function current(){return ParityApp.getState();}
function libertyReadout(s,i){const g=BioEngine.group(s.board,i),count=BioEngine.libs(s.board,g).length,shown=Math.min(count,12),dots=Array.from({length:shown},(_,n)=>{const a=n*Math.PI*2/shown-Math.PI/2;return `<i class="bio-liberty-dot" style="--liberty-x:${(50+47*Math.cos(a)).toFixed(1)}%;--liberty-y:${(50+47*Math.sin(a)).toFixed(1)}%"></i>`;}).join('');return `<span class="bio-liberty-ring" aria-hidden="true">${dots}</span>`;}
function formatEvent(e){if(!e.kind)return null;const who=e.color==='black'?'黑':'白',k={place:`${F[e.faction]||''}${roman[e.tier]||''}`,migration:'迁移选点',divide:'二分裂',interfere:'抗真菌干扰',end:'结束回合',pass:'停一手'}[e.kind]||e.kind;return `${who} · ${k}${e.point===null?'':' '+BioEngine.coord(e.point)}${e.cost?' −'+e.cost+' VP':''}${e.captured?' · 提'+e.captured:''}${e.destinations.length?' → '+e.destinations.map(BioEngine.coord).join('、'):''}${e.removed?' · 移除'+e.removed:''}${e.details?.length?' · '+e.details.join('；'):''}`;}
function prepare(s,i){if(!s.bioMode)return i;if(s.phase==='migration')return {point:i};if(s.phase==='bonus'){const actions=BioEngine.bonusActions(s);if(BioEngine.meta(s,i)?.faction==='bacteria'&&s.board[i]?.color===s.turn){source=i;window.game.updateUI();return {uiOnly:true};}const match=actions.find(a=>a.type===ability&&a.point===i&&(source===null||BioEngine.bacterialGroup(s,source).includes(a.source)));return match||{type:ability||'end-invalid',point:i};}return {point:i,faction:selected[s.turn].faction};}
function decorate(el,s){if(!s.bioMode)return;const points=el.querySelectorAll('.parity-point');points.forEach((b,i)=>{const p=s.board[i];if(!p)return;const m=BioEngine.meta(s,i);if(p.kind==='spore'){b.innerHTML=`<span class="bio-spore ${p.dead?'dead':''}" title="${p.dead?'永久中性死点':'孢子：'+m.sporeTimer+' 回合'}">${icon('fungi')}<b>${p.dead?'×':m.sporeTimer}</b></span>`;b.setAttribute('aria-label',BioEngine.coord(i)+' '+(p.dead?'死点':'孢子'));return;}const stone=b.querySelector('.parity-stone');if(!stone||!m)return;const liberties=BioEngine.libs(s.board,BioEngine.group(s.board,i)).length;stone.classList.add('bio-stone',m.faction);stone.innerHTML=`${icon(m.faction)}<span class="bio-tier">${roman[m.tier]}</span>${libertyReadout(s,i)}${p.migrated?'<small class="bio-migrated">↻</small>':''}${m.infectionCount?'<b class="bio-badge infection">'+m.infectionCount+'</b>':''}${m.resistanceCount?'<b class="bio-badge resistance">'+m.resistanceCount+'</b>':''}${BioEngine.bacterialGroup(s,i).length>=2?'<span class="bio-film"></span>':''}`;b.title=BioEngine.coord(i)+' · '+F[m.faction]+' '+roman[m.tier]+' · '+(s.board[i].color==='black'?'黑':'白')+' · '+liberties+' 口气'+(m.divisionReady>s.bio.round?' · 分裂冷却 '+(m.divisionReady-s.bio.round):'');b.setAttribute('aria-label',BioEngine.coord(i)+' '+(s.board[i].color==='black'?'黑':'白')+F[m.faction]+'，'+liberties+' 口气');});
 if(el.id==='board'){const targets=s.phase==='migration'?s.pending.choices:s.phase==='bonus'?BioEngine.bonusActions(s).filter(a=>a.type===ability&&(source===null||BioEngine.bacterialGroup(s,source).includes(a.source))).map(a=>a.point):[];points.forEach((b,i)=>b.classList.toggle('bio-target',targets.includes(i)));}
}
function render(s){if(!$('bioPanel'))return;$('bioPanel').hidden=false;const color=s.turn,pick=selected[color],own=s.bio.factions?.[color],enemy=s.bio.factions?.[color==='black'?'white':'black'],pair=s.bio.factions?.black&&s.bio.factions?.white?` · 黑${F[s.bio.factions.black]} vs 白${F[s.bio.factions.white]}`:'';$('bioPhase').textContent=s.over?'对局结束：'+(s.winner==='draw'?'和棋':s.winner==='black'?'黑方胜':'白方胜'):s.phase==='migration'?((own==='bacteria'?'细菌':'真菌')+'迁移：请从高亮点位指定迁移位置'):'第 '+(s.ply+1)+' 手 · '+(color==='black'?'黑':'白')+'方'+(own?'（'+F[own]+'）':'选择派系后')+'落子'+pair;document.querySelectorAll('[data-faction]').forEach(b=>{b.classList.toggle('active',b.dataset.faction===(own||pick.faction));b.disabled=s.phase!=='place'||(own&&b.dataset.faction!==own)||(!own&&b.dataset.faction===enemy);});$('bioPass').disabled=s.over||s.phase==='migration';$('bioPass').textContent='停一手';$('bioCost').textContent=pick.faction==='virus'?'病毒：第3次被提直接剔除；此前最短路径替换':pick.faction==='bacteria'?'细菌：自由选择己方菌群气孔，不限距离；第3次被提剔除':'真菌：第3次被提剔除；此前点击高亮气孔迁移';const a=BioEngine.score(s);$('bioComposition').innerHTML=['black','white'].map(c=>'<div class="composition-row"><span>'+ (c==='black'?'黑':'白')+'</span>'+Object.keys(F).map(f=>'<span class="'+f+'">'+icon(f)+' '+a.factions[c][f]+'</span>').join('')+'</div>').join('')+'<small>中性孢子 / 死点 '+a.infectedArea+'</small>';}
function editStone(s,i,brush){if(!s.bioMode)return;const old=s.board[i];if(old?.id){delete s.bio.stoneMeta[old.id];delete s.bio.sporeMarkers[old.id];}if(brush==='empty')s.board[i]=null;else{const id='b'+s.bio.nextId++,pick=selected[s.turn];s.bio.stoneMeta[id]=BioFeatures.createStoneMeta(pick.faction,pick.tier,brush);s.board[i]={id,color:brush,migrated:false};}s.phase='place';delete s.pending;}
let bioAudio=null;
function audio(){if(bioAudio)return bioAudio;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;bioAudio=new C();return bioAudio;}catch{return null;}}
function bioTone(ctx,at,{hz=440,to=hz,duration=.12,type='sine',gain=.05}){const osc=ctx.createOscillator(),amp=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(hz,at);osc.frequency.exponentialRampToValueAtTime(Math.max(1,to),at+duration);amp.gain.setValueAtTime(.0001,at);amp.gain.exponentialRampToValueAtTime(gain,at+.012);amp.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(amp).connect(ctx.destination);osc.start(at);osc.stop(at+duration+.02);}
function soundFaction(e,before){if(e.faction)return e.faction;const pending=before?.pending;if(pending?.faction)return pending.faction;const stone=pending?.captured?.[pending.cursor]?.stone;return stone?.id?before?.bio?.stoneMeta?.[stone.id]?.faction:null;}
function playEventSound(e,before){if(!e||!before?.bioMode)return;const faction=soundFaction(e,before);if(!faction)return;const ctx=audio();if(!ctx)return;if(ctx.state==='suspended')ctx.resume().catch(()=>{});const t=ctx.currentTime+.015;
 const place={virus:()=>{bioTone(ctx,t,{hz:670,to:470,duration:.09,type:'triangle',gain:.045});bioTone(ctx,t+.055,{hz:910,to:740,duration:.07,type:'sine',gain:.025});},bacteria:()=>{bioTone(ctx,t,{hz:180,to:145,duration:.11,type:'sine',gain:.06});bioTone(ctx,t+.055,{hz:270,to:220,duration:.09,type:'sine',gain:.035});},fungi:()=>{bioTone(ctx,t,{hz:330,to:250,duration:.14,type:'triangle',gain:.055});bioTone(ctx,t+.035,{hz:495,to:370,duration:.12,type:'sine',gain:.022});}};
 const migrate={virus:()=>{bioTone(ctx,t,{hz:240,to:900,duration:.16,type:'sawtooth',gain:.035});bioTone(ctx,t+.08,{hz:680,to:1080,duration:.1,type:'triangle',gain:.025});},bacteria:()=>{[0,.055,.11].forEach((d,i)=>bioTone(ctx,t+d,{hz:135+i*42,to:105+i*31,duration:.1,type:'sine',gain:.045}));},fungi:()=>{bioTone(ctx,t,{hz:380,to:570,duration:.2,type:'sine',gain:.04});bioTone(ctx,t+.07,{hz:570,to:760,duration:.17,type:'triangle',gain:.03});}};
 if(e.kind==='place')place[faction]();
 if(e.kind==='migration')migrate[faction]();
 // 病毒替换在同一手落子事件中完成，因此补一段迁移提示音。
 if(e.kind==='place'&&e.destinations?.length&&faction==='virus')setTimeout(()=>migrate.virus(),115);
}
const ruleBlocks=[['先看这三件事','你控制黑子或白子。轮流点击棋盘线的交叉点落一子；黑方先下。游戏结束时，盘上的棋子加上被自己围住的空点，谁多谁赢。'],['什么叫“气”？','棋子上下左右紧挨着的空点，就是它的“气”（可呼吸的位置）。斜着不算相连，也不算气。相邻的同色棋子会连成一块，并共享所有气。'],['怎样吃子？','把对方一块棋周围最后的气填上，这一整块棋就被“提掉”。你的棋落下后也必须至少有一口气，所以不能把自己下进完全封死的位置。'],['提掉后会发生什么？','被提棋子的原位置，会永久禁止同色普通落子回填；对手可以落。迁移不是额外回合：迁移处理完，仍轮到被提的一方正常落子。'],['先选一个派系','每方第一次落子前，从病毒、细菌、真菌中选一个。选定后整局只能用这一派系；两方不能选同一种。派系只看图标和名称。'],['病毒：自动替换','病毒第 1、2 次被提时：如果吃子方有两颗或更多相连棋子，系统会把离被提位置最近的一颗吃子方棋子移到可存活位置进行替换；没有可替换目标就移除。'],['细菌：连到菌群','细菌第 1、2 次被提时：从“已有己方细菌旁边的空点”中选一个高亮点迁移，不限距离。迁入后，新细菌和相连的细菌都必须还有气；没有合法点就移除。'],['真菌：自由找气','真菌第 1、2 次被提时：从吃子方留下的高亮气点中任选一处迁移，不限距离。迁入后必须仍有气；没有合法点就移除。'],['第三次被提','同一颗棋子已经迁移过两次后，第 3 次被提不再发动任何派系效果，直接从棋盘移除。'],['什么时候结束？','双方连续各停一手、棋盘填满，或有人认输 / 双方同意和棋时结束。若某方连续两次轮到自己都没有合法落点，系统也会立刻结算，不会让另一方无限继续落子。']];
function rules(){ $('rulesModalContent').innerHTML='<h3>生物棋 · 新手规则</h3><p class="bio-rule-intro">不用会围棋。第一次玩时，只要按顺序读完前 3 条，就可以开始落子。</p><div class="parity-rules">'+ruleBlocks.map(([h,t],i)=>`<h4>${i+1}. ${h}</h4><p>${t}</p>`).join('')+'</div>';$('rulesModal').classList.add('active');}
const tutorialSteps=[
 ['欢迎来到生物棋','不用会围棋。你只需记住：轮流落子、保留“气”、堵住对手最后一口气就能吃子。黑方先下。','sides'],
 ['棋子应该下在哪里？','点击棋盘线与线相交的点落子，不是格子中央。每次只能下一颗；不能落在已有棋子、死点或自己的禁回填点上。','board'],
 ['什么是“气”？','棋子上下左右紧挨着的空交叉点，就是它的“气”，可以理解成呼吸空间。棋子边缘的小点会实时显示还有哪些气；斜对角不算气。','liberty'],
 ['同色棋子会连在一起','上下左右相连的同色棋子会成为同一块棋，并共享全部气。想救一颗快没气的棋子，可以在它旁边落同色棋来增加共同的气。','group'],
 ['怎样吃掉对手？','把对方一整块棋周围最后的气堵住，这一整块棋就会被提起。自己的新棋也必须有至少一口气，所以不能把自己下进完全封死的位置。','capture'],
 ['提子后不用停一回合','被提的一方会先按派系效果处理迁移；迁移完成后，仍然轮到被提的一方正常落子。被提棋子原来的位置，对该颜色以后不能普通回填。','migration'],
 ['先选派系，再落第一子','每方第一次落子前选择病毒、细菌或真菌。选定后整局不变；对手不能选择和你相同的派系。黑白深浅表示双方，派系只看图标和名称。','factions'],
 ['病毒：自动替换','病毒在第 1、2 次被提时，若吃子方有相连的棋子，系统会从最近的相连棋子中自动选择一颗进行替换迁移。没有可存活的位置时才移除。','virus'],
 ['细菌和真菌：你来选位置','细菌被提后，可迁到任一已有己方细菌旁的空点；真菌被提后，可迁到吃子方留下的高亮气点。两者都不受距离限制，迁入后必须仍有气。高亮时点击目标点即可。','choice'],
 ['第三次被提与胜负','同一颗棋子前两次被提会发动派系效果；第 3 次被提直接移除。若一方连续两次轮到自己都没有合法落点，也会自动结算；棋子加自己围住的空点更多的一方获胜。','end']
];
function tutorialVisual(kind){
 const stone=(color,f='virus')=>`<span class="bio-tutorial-stone ${color}">${icon(f)}<i></i><i></i><i></i><i></i></span>`;
 if(kind==='sides')return `<div class="bio-guide-visual bio-guide-sides">${stone('black')}<b>黑方先下</b>${stone('white')}<b>白方后下</b></div>`;
 if(kind==='board')return '<div class="bio-guide-board" aria-label="落子在交叉点"><i></i><i></i><i></i><i></i><i></i><i class="target"></i><i></i><i></i><i></i></div>';
 if(kind==='liberty')return `<div class="bio-guide-visual">${stone('black','bacteria')}<span class="bio-guide-note">边缘小点 = 还有气</span></div>`;
 if(kind==='group')return `<div class="bio-guide-visual bio-guide-group">${stone('black','fungi')}${stone('black','fungi')}<span>相连后共享气</span></div>`;
 if(kind==='capture')return `<div class="bio-guide-capture"><span class="enemy">${stone('white')}</span><span>用自己的棋堵住<br>最后一个空点</span></div>`;
 if(kind==='migration')return '<div class="tutorial-key"><b>提子</b><span>→</span><b>迁移处理</b><span>→</span><b>被提方继续下</b></div>';
 if(kind==='factions'||kind==='choice')return `<div class="bio-guide-icons">${Object.keys(F).map(f=>`<span>${icon(f)}<b>${F[f]}</b></span>`).join('')}</div>`;
 if(kind==='virus')return `<div class="bio-guide-visual bio-guide-group">${stone('black','virus')}<span>相连棋子可自动替换</span></div>`;
 return '<div class="tutorial-key"><b>第 1 次</b><span>派系效果</span><b>第 2 次</b><span>派系效果</span><b>第 3 次</b><span>直接移除</span></div>';
}
function tutorial(n=0){const step=tutorialSteps[n];$('tutorialModalContent').innerHTML=`<span class="bio-eyebrow">新手引导 / ${n+1} OF ${tutorialSteps.length}</span><h3>${step[0]}</h3><p>${step[1]}</p>${tutorialVisual(step[2])}<p class="bio-tutorial-tip"><b>记住：</b>${n<5?'先找气，再想吃子。':n<9?'派系图标决定提子后的特殊处理。':'终局会由系统自动结算。'}</p><div class="tutorial-nav"><button id="bioPrev" class="tutorial-btn" ${n===0?'disabled':''}>上一步</button><button id="bioSkip" class="tutorial-btn">跳过教学</button><button id="bioNext" class="tutorial-btn primary">${n===tutorialSteps.length-1?'开始对局':'下一步'}</button></div>`;$('bioPrev').onclick=()=>tutorial(n-1);$('bioSkip').onclick=()=>$('tutorialModal').classList.remove('active');$('bioNext').onclick=()=>n===tutorialSteps.length-1?$('tutorialModal').classList.remove('active'):tutorial(n+1);$('tutorialModal').classList.add('active');}
function trends(){if(!$('bioTrend'))return;const record=ParityApp.record();if(!record.state.bioMode){$('bioTrend').hidden=true;return;}$('bioTrend').hidden=false;const series=record.history.map(s=>BioEngine.score(s).factions);$('bioTrend').innerHTML='<h4>派系构成 / 随结算变化</h4>'+['black','white'].map(c=>`<div class="bio-trend-title">${c==='black'?'黑方':'白方'}</div><svg viewBox="0 0 360 64" role="img" aria-label="${c}三派系数量变化">${series.map((s,i)=>{let y=62;return Object.keys(F).map(f=>{const h=s[c][f]/36*60;y-=h;return `<rect class="${f}" x="${i*360/series.length}" y="${y}" width="${Math.max(1,360/series.length)}" height="${h}"/>`;}).join('');}).join('')}</svg>`).join('');}
window.BioUI={prepare,decorate,render,formatEvent,editStone,playEventSound};
window.addEventListener('DOMContentLoaded',()=>{
 document.body.classList.add('bio-design');document.title='生物棋 · 三派系博弈';$('sidePanelTitle').innerHTML='<span class="bio-eyebrow">BIO / STRATEGY LAB</span>生物棋';$('sidePanelTitle').insertAdjacentHTML('afterend','<div id="bioPhase" class="bio-phase"></div><section id="bioPanel"><div class="bio-section-label">选择落子 / ORGANISM</div><div class="bio-factions">'+Object.keys(F).map(f=>`<button data-faction="${f}" class="${f}">${icon(f)}<span>${F[f]}</span></button>`).join('')+'</div><p id="bioCost"></p><button id="bioPass">结束回合</button><div id="bioComposition"></div></section>');
 document.querySelectorAll('[data-faction]').forEach(b=>b.onclick=()=>{const s=current(),enemy=s.bio.factions?.[s.turn==='black'?'white':'black'];if(enemy===b.dataset.faction)return;selected[s.turn].faction=b.dataset.faction;window.game.updateUI();});$('bioPass').onclick=()=>$('btnPass').click();$('btnRules').onclick=rules;$('btnTutorial').onclick=()=>tutorial();
 $('reviewChartContainer').insertAdjacentHTML('afterend','<div id="bioTrend"></div>');new MutationObserver(trends).observe($('reviewOverlay'),{attributes:true,attributeFilter:['class']});
 const theme=window.ParityTheme;theme.PRESETS.bio={...theme.PRESETS.classic,whiteCell:'#e2eee6',blackCell:'#597b70',bodyBg:'#edf2ee',boardBg:'#ceddd2',boardBorder:'#89a398',panelBg:'#fafcf9',panelColor:'#203c35',panelHeading:'#497568',wpStart:'#ffffff',wpEnd:'#e4eee6',bpStart:'#40564e',bpEnd:'#122b24',selected:'#b78d54'};$('themePresetChips').insertAdjacentHTML('beforeend','<span class="theme-preset-chip" data-preset="bio">生物棋</span>');document.querySelector('[data-preset="bio"]').onclick=()=>{theme.applyPreset('bio');theme.syncUI();};if(!localStorage.getItem('bio_go_theme'))theme.applyPreset('bio');$('btnElements').title='派系与资源说明';$('btnElements').onclick=rules;window.game.updateUI();
});
})();
