const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./bio-engine'),P=require('./parity-engine'),B=require('./bio-features');
function fixture(f,seed=3){const s=E.initial(seed);s.bio.factions={black:'virus',white:f};const add=(i,c,t=f)=>{const id='b'+s.bio.nextId++;s.board[i]={id,color:c};s.bio.stoneMeta[id]=B.createStoneMeta(t,1,c);};add(7,'black','virus');add(12,'black','virus');add(6,'white');return {s,add};}
for(let seed=1;seed<=20;seed++){const {s,add}=fixture('bacteria',seed);add(20,'white');let r=E.play(s,{point:0,faction:'virus'});assert.ok(!r.error);assert.equal(r.state.phase,'migration');assert.deepEqual(new Set(r.state.pending.choices),new Set([14,19,21,26]));assert.deepEqual(E.play(s,{point:0,faction:'virus'}),r);r=E.play(r.state,{point:26});assert.equal(r.state.phase,'place');assert.equal(r.state.turn,'white');assert.equal(r.event.destinations.length,1);assert.equal(r.event.destinations[0],26);for(const i of [20,...r.event.destinations])assert.ok(P.libs(r.state.board,E.group(r.state.board,i)).length);assert.equal(s.board[6].color,'white');}
{const {s}=fixture('bacteria');const r=E.play(s,{point:0,faction:'virus'});assert.equal(r.event.removed,1);assert.equal(r.event.destinations.length,0);assert.notEqual(r.state.phase,'migration');}
{const {s,add}=fixture('fungi');add(35,'black','virus');const r=E.play(s,{point:0,faction:'virus'});assert.equal(r.state.phase,'migration');assert.equal(r.state.board[6],null);assert.ok(r.state.pending.choices.includes(34));const t=E.play(r.state,{point:34});assert.ok(!t.error);assert.equal(t.state.turn,'white');assert.equal(t.state.phase,'place');assert.ok(P.libs(t.state.board,E.group(t.state.board,34)).length);assert.ok(!t.state.board.some(p=>p?.kind==='spore'));assert.ok(E.play(r.state,{point:6}).error);}
{const s=E.initial(1);s.phase='migration';s.pending={actor:'black',cursor:0,captured:[{origin:0,stone:{id:'victim',color:'white'}}],choices:[]};s.bio.stoneMeta.victim=B.createStoneMeta('fungi',1,'white');s.turn='white';const r=E.pass(s);assert.equal(r.event.removed,1);assert.equal(r.state.phase,'place');assert.equal(r.state.turn,'white');}
{const s=E.initial(77),add=(i,c,f)=>{const id='b'+s.bio.nextId++;s.board[i]={id,color:c};s.bio.stoneMeta[id]=B.createStoneMeta(f,1,c);return id;};const dead=add(0,'black','virus');add(1,'white','fungi');add(6,'white','fungi');const r=E.pass(s);assert.equal(r.state.board[0],null);assert.equal(r.state.bio.stoneMeta[dead],undefined);assert.ok(r.state.locks.black.includes(0));assert.equal(r.event.removed,1);assert.match(r.event.details.join(' '),/全局结算/);for(let i=0;i<36;i++)if(r.state.board[i]&&r.state.board[i].kind!=='spore')assert.ok(P.libs(r.state.board,E.group(r.state.board,i)).length,'settled '+i);}

{const s=E.initial(78),add=(i,c)=>{const id='b'+s.bio.nextId++;s.board[i]={id,color:c};s.bio.stoneMeta[id]=B.createStoneMeta('virus',1,c);return id;};const dead=add(0,'black');add(1,'white');add(6,'white');E.finish(s,'测试结算');assert.equal(s.phase,'finished');assert.equal(s.board[0],null);for(let i=0;i<36;i++)if(s.board[i]&&s.board[i].kind!=='spore')assert.ok(P.libs(s.board,E.group(s.board,i)).length,'finished '+i);}

{const s=E.initial(79),add=(i,c)=>{const id='b'+s.bio.nextId++;s.board[i]={id,color:c};s.bio.stoneMeta[id]=B.createStoneMeta('virus',1,c);};add(0,'black');add(1,'white');add(6,'white');s.over=true;s.phase='finished';assert.equal(E.valid(s),false);}

for(const f of ['bacteria','fungi']){const {s}=fixture(f,90);const id=s.board[6].id;s.bio.stoneMeta[id].captureCount=2;const r=E.play(s,{point:0,faction:'virus'});assert.ok(!r.error);assert.equal(r.state.bio.stoneMeta[id],undefined,f+' third capture metadata');assert.equal(r.state.board[6],null,f+' third capture origin');assert.equal(r.state.pending,undefined,f+' third capture must not wait migration');assert.equal(r.state.phase,'place',f+' third capture next phase');assert.equal(r.event.destinations.length,0,f+' third capture no migration');assert.equal(r.event.removed,1,f+' third capture removed');assert.match(r.event.details.join(' '),/第3次被提/);}

const html=fs.readFileSync(__dirname+'/Chemiss-UI-基线.html','utf8');assert.ok(html.includes(fs.readFileSync(__dirname+'/bio-engine.js','utf8').trim()));
console.log('v3 migration: nearest/ties, no anchor removal, fungi free choice, no spores, exhaustion, source purity, inline sync passed');
