/* Controller for the original Chemiss panels and toolbar, adapted to 6x6 Go. */
(()=>{
'use strict';
const E=ParityEngine,$=id=>document.getElementById(id),on=(id,fn)=>{if($(id))$(id).onclick=fn;},escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let gameNonce=0;
function newGameSeed(){let entropy=0;try{const values=new Uint32Array(1);crypto.getRandomValues(values);entropy=values[0];}catch{entropy=(Math.random()*0xffffffff)>>>0;}gameNonce=(gameNonce+1)>>>0;return (entropy^Date.now()^(performance.now()*1000>>>0)^Math.imul(gameNonce,0x9e3779b9))>>>0||1;}
function autoPair(s){if(!s.bioMode||s.ply||s.bio.factions.black||s.bio.factions.white)return false;const pool=['virus','bacteria','fungi'];let x=(s.seed^0xa511e9b3)>>>0;for(let i=pool.length-1;i>0;i--){x^=x<<13;x^=x>>>17;x^=x<<5;const j=(x>>>0)%(i+1);[pool[i],pool[j]]=[pool[j],pool[i]];}s.bio.factions.black=pool[0];s.bio.factions.white=pool[1];return true;}
let state=E.initial(newGameSeed()),history=[E.copy(state)],events=[],mode='local',aiColor='white',level=4,levels={black:4,white:4},flipped=false,coords=true,editing=false,brush='black',reviewAt=null,aiToken=0,worker=null,pending=null,room=null,peerId=null,version=0,joined=false,clockActive=false,clockTime={black:300000,white:300000},increment=2000,lastTick=performance.now();
let requested=null;
const name=c=>c==='black'?'黑方':c==='white'?'白方':'和棋';
function close(id){$(id)?.classList.remove('active');document.body.classList.remove('modal-open');}
function open(id){cancelAI();$(id).classList.add('active');document.body.classList.add('modal-open');}
function message(text){$('selectedInfo').textContent=text;}
function toggleSidebar(force){const hidden=typeof force==='boolean'?force:!document.body.classList.contains('sidebar-hidden');document.body.classList.toggle('sidebar-hidden',hidden);const button=$('btnSidebar');if(button){button.classList.toggle('active',hidden);button.title=hidden?'显示侧边栏':'隐藏侧边栏';button.setAttribute('aria-label',button.title);}try{localStorage.setItem('bio_go_sidebar_hidden',hidden?'1':'');}catch{}return hidden;}
function modal(title,html){$('nuclearModalContent').innerHTML=`<h3>${escape(title)}</h3>${html}<button class="theme-btn" id="dismissDialog">关闭</button>`;open('nuclearModal');on('dismissDialog',()=>{close('nuclearModal');schedule();});}
function note(e){const bio=window.BioUI?.formatEvent(e);if(bio)return bio;return `${name(e.color)} ${e.point===null?'停一手':E.coord(e.point)}${e.captured?` · 提${e.captured} → 迁${e.destinations.length}（${e.destinations.map(E.coord).join('、')||'无'}）/ 除${e.removed}`:''}`;}
function drawBoard(el,s,interactive=false){el.innerHTML='';el.classList.add('parity-board');const lines=document.createElementNS('http://www.w3.org/2000/svg','svg');lines.setAttribute('viewBox','0 0 600 600');lines.classList.add('parity-lines');lines.innerHTML=Array.from({length:6},(_,n)=>`<path d="M50 ${50+n*100} H550 M${50+n*100} 50 V550"/>`).join('');el.append(lines);
 for(let i=0;i<36;i++){const display=flipped?35-i:i,stone=s.board[i],b=document.createElement('button');b.type='button';b.className='parity-point';b.style.left=(display%6*100/6+100/12)+'%';b.style.top=(Math.floor(display/6)*100/6+100/12)+'%';b.setAttribute('aria-label',E.coord(i)+(stone?' '+name(stone.color):' 空点'));b.title=E.coord(i);if(stone){const p=document.createElement('span');p.className='parity-stone '+stone.color+(s.last===i?' last':'');p.textContent=stone.migrated?'↻':'';b.append(p);}else if(s.locks[s.turn].includes(i)){b.classList.add('locked');b.title+=' · '+name(s.turn)+'禁回填';}if([7,10,25,28].includes(i)&&!stone)b.classList.add('star');if(interactive)b.onclick=()=>{if(editing){if(state.bioMode)window.BioUI.editStone(state,i,brush);else state.board[i]=brush==='empty'?null:{color:brush,migrated:false};state.ply=0;state.last=null;state.passes=0;state.over=false;state.winner=null;state.reason='';state.locks={black:[],white:[]};state.seen=[E.hash(state)];history=[E.copy(state)];events=[];render();}else action(i);};else b.disabled=true;el.append(b);}
 if(coords)for(let n=0;n<6;n++){const c=document.createElement('span');c.className='parity-coordinate col';c.style.left=(n*100/6+100/12)+'%';c.textContent=String.fromCharCode(65+(flipped?5-n:n));el.append(c);const r=document.createElement('span');r.className='parity-coordinate row';r.style.top=(n*100/6+100/12)+'%';r.textContent=flipped?n+1:6-n;el.append(r);}
 window.BioUI?.decorate(el,s);
}
function render(){drawBoard($('board'),state,true);const s=E.score(state);$('turnIndicator').textContent=state.over?'对局结束 · '+name(state.winner)+(state.winner==='draw'?'':'胜'):name(state.turn)+'落子';$('turnIndicator').className='turn-indicator turn-'+state.turn;$('roundCounter').textContent=`第 ${state.ply+1} 手 · ${editing?'局面编辑':({local:'双人对战',ai:'人机对战',auto:'AI 对弈',online:'联机对战'})[mode]}`;$('bondList').innerHTML=`<div class="parity-score"><div>黑方<b>${s.black}</b><small>棋子 ${s.stones.black} · 围空 ${s.territory.black}</small></div><div>白方<b>${s.white}</b><small>棋子 ${s.stones.white} · 围空 ${s.territory.white}</small></div></div><small>未定归属 ${s.neutral} · ↻ 迁移子 · × 当前执子方禁点</small>`;$('logPanel').textContent=events.map(note).join('\n');$('notationList').innerHTML=events.map((e,i)=>`<div>${i+1}. ${escape(note(e))}</div>`).join('');['aiDiffRow','aiModelRow','aiColorRow'].forEach(id=>$(id).style.display=['ai','auto'].includes(mode)?'flex':'none');$('aiModelValue').textContent='生物棋搜索 AI';$('btnAI').classList.toggle('active',mode==='ai');$('btnAutoPlay').classList.toggle('active',mode==='auto');document.querySelectorAll('.ai-diff-chip').forEach(b=>b.classList.toggle('active',+b.dataset.lv===level));document.querySelectorAll('.ai-color-chip').forEach(b=>b.classList.toggle('active',b.dataset.color===aiColor));window.BioUI?.render(state);}
function cancelAI(){aiToken++;if(pending){clearTimeout(pending);pending=null;}if(worker){worker.terminate();worker=null;}}
function schedule(){cancelAI();if(state.over||editing||reviewAt!==null||document.querySelector('.modal-overlay.active'))return;if(mode!=='auto'&&!(mode==='ai'&&state.turn===aiColor))return;const token=aiToken;pending=setTimeout(()=>{message('AI 正在思考…');const lv=mode==='auto'?levels[state.turn]:level;const done=r=>{if(token!==aiToken)return;worker=null;message(`AI 深度 ${r.depth||1} · 搜索 ${r.nodes||0} 个节点`);commit(r.point);};
 try{const text=$('parity-engine').textContent+'\nonmessage=e=>postMessage(ParityEngine.choose(e.data.s,e.data.level));';const url=URL.createObjectURL(new Blob([text],{type:'application/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{worker.terminate();done(e.data);};worker.onerror=()=>{worker.terminate();worker=null;done(E.choose(state,lv,180));};worker.postMessage({s:state,level:lv});}catch{done(E.choose(state,lv,180));}},450);}
function action(point){if(state.over)return message('对局已结束：'+state.reason+'。可查看复盘或重新开始。');if(editing)return;if(mode==='auto'||(mode==='ai'&&state.turn===aiColor))return message('当前由 AI 执子，请先暂停 AI 对弈。');if(typeof point==='number'){point=window.BioUI?.prepare(state,point)??point;if(point?.uiOnly)return;}if(mode==='online'){if(!room?.connected||!room._peerOnline||!joined)return message('等待对手连接并同步局面。');if(state.turn!==room.localColor)return message('请等待对手落子。');if(!room.isHost){room.send({type:'action',point,version});return;}}commit(point);}
function commit(point){const before=state,r=point===null?E.pass(state):E.play(state,point);if(r.error)return message(r.error);if(clockActive&&r.state.ply>state.ply)clockTime[state.pending?.actor||state.turn]+=increment;window.BioUI?.playEventSound(r.event,before);state=r.state;events.push(r.event);history.push(E.copy(state));version++;render();message(note(r.event));if(room?.isHost)sendState();if(state.over)victory();else schedule();}
function victory(){cancelAI();clockActive=false;const a=E.score(state);modal('对局结束',`<div class="parity-result"><h2>${name(state.winner)}${state.winner==='draw'?'':'胜'}</h2><p>${escape(state.reason)}</p><p>黑方 ${a.black}　:　白方 ${a.white}</p><p>计分：盘上棋子 + 单色围空</p><button class="theme-btn" id="resultReview">查看复盘</button><button class="theme-btn" id="resultNew">再来一局</button></div>`);on('resultReview',()=>{close('nuclearModal');review();});on('resultNew',()=>{close('nuclearModal');reset();});}
function reset(force=false){if(mode==='online'&&!force)return requestRemote('reset');cancelAI();state=E.initial(newGameSeed());if(mode==='auto')autoPair(state);history=[E.copy(state)];events=[];version++;clockActive=false;clockTime={black:+$('clockNumInput').value*60000,white:+$('clockNumInput').value*60000};render();schedule();}
function undo(force=false){if(mode==='online'&&!force)return requestRemote('undo');cancelAI();if(history.length<2)return message('没有可以回退的着手。');const n=mode==='ai'&&history.length>2?2:1;history.splice(-n);events.splice(-n);state=E.copy(history.at(-1));version++;clockActive=false;render();schedule();}
function setMode(m){if(room)disconnect();cancelAI();const startFreshAuto=m==='auto'&&state.over;mode=m;editing=false;document.body.classList.remove('debug-active');if(startFreshAuto){state=E.initial(newGameSeed());autoPair(state);history=[E.copy(state)];events=[];version++;}else if(m==='auto'&&autoPair(state)){history=[E.copy(state)];events=[];version++;}render();schedule();}
function rules(){ $('rulesModalContent').innerHTML=`<h3>生物棋 · 游戏规则</h3><div class="parity-rules">${[
 ['游戏目标','黑先白后，在 6×6 棋盘交叉点落子。终局按棋子与围空之和计分，多者获胜。'],
 ['棋块与气','同色棋子沿上下左右相连形成棋块。相邻的空交叉点是气。落子不能自杀；无气的对方棋块被提起。'],
 ['三次被提','同一棋子第 1、2 次被提时按派系规则处理；第 3 次被提时不再迁移或替换，直接剔除。'],
 ['病毒迁移','病毒在第 1、2 次被提时，替换提子方相连棋子中距离被提位置最近的一枚。'],
 ['细菌迁移','细菌在第 1、2 次被提时，由被提方玩家或 AI 自由选择己方其他现存细菌的相邻气孔，不限距离，迁入棋子和已有菌群都必须保有气。'],
 ['真菌迁移','真菌在第 1、2 次被提时，由被提方点击高亮的提子方气孔自由迁移；不受最短路径限制，迁入后必须有气。'],
 ['颜色禁回填','某色棋子被提离开的交叉点永久禁止该色正常落子回填，对手不受此限制；本次迁移也不能回到本次被提原位。'],
 ['轮次与标记','迁移不占用被提一方的落子回合。↻ 表示迁移子，外圈标记上一手，× 表示当前一方的禁回填点。'],
 ['终局与胜负','双方连续停一手、双方均无着可下、满盘时自动结算；若某一方连续两次轮到自己都没有合法落点，也会立即结算，避免另一方无限继续落子。可以认输，也可双方同意和棋。显示的即时面积不等于已经终局。']].map(([h,p],i)=>`<h4>${i+1}. ${h}</h4><p>${p}</p>`).join('')}</div>`;open('rulesModal');}
const lessons=[['认识棋盘','棋子落在交叉点上，黑方先手。请点击 C3 试下一颗黑子。',20],['棋块与气','上下左右的空点是气；同色相连后共享气。图中黑子周围的空点都可成为气。',null],['提子','请点击 A6，把 A5 白子的最后一口气堵住，观察它的迁移。',0],['迁移与最短路径','被提棋子在提子方全部气孔中寻找最近可存活落点。同距随机，不能返回本次被提原位。',null],['禁回填','原位会对被提颜色永久锁定。对手仍可落子，迁移结束后仍轮到被提一方。',null],['结束与复盘','双方连续停一手可以结束。系统会显示比分与胜者，复盘可逐手查看包括随机迁移在内的真实局面。',null],['开始对局','工具栏可切换人机、AI 对弈、联机、主题。教学棋盘独立于对局，关闭即可继续原来的棋。',null]];
function tutorial(n=0){let demo=E.initial(42,{mode:false});if(n===1)demo.board[20]={color:'black',migrated:false};if(n>=2&&n<=4){[7,12].forEach(i=>demo.board[i]={color:'black',migrated:false});demo.board[6]={color:'white',migrated:false};if(n>2)demo=E.play(demo,0,{checkEnd:false}).state;}const [title,body,target]=lessons[n];$('tutorialModalContent').innerHTML=`<div class="tutorial-step-label">${n+1} / ${lessons.length}</div><h3>${title}</h3><p>${body}</p><div id="lessonBoard" class="parity-mini"></div><p id="lessonFeedback"></p><div class="tutorial-nav"><button class="tutorial-btn" id="tutPrev" ${n===0?'disabled':''}>上一步</button><span>${lessons.map((_,i)=>i===n?'●':'○').join(' ')}</span><button class="tutorial-btn primary" id="tutNext" ${target!==null?'disabled':''}>${n===6?'完成':'下一步'}</button></div><button class="tutorial-btn" id="tutSkip">跳过教学</button>`;drawBoard($('lessonBoard'),demo);if(target!==null)Array.from($('lessonBoard').querySelectorAll('.parity-point')).forEach((b,i)=>{b.disabled=false;b.onclick=()=>{if(i!==target){$('lessonFeedback').textContent='试试 '+E.coord(target)+'。';return;}const r=E.play(demo,i,{checkEnd:false});drawBoard($('lessonBoard'),r.state);$('lessonFeedback').textContent='完成！'+note(r.event);$('tutNext').disabled=false;};});on('tutPrev',()=>tutorial(n-1));on('tutNext',()=>{if(n===6){close('tutorialModal');schedule();}else tutorial(n+1);});on('tutSkip',()=>{close('tutorialModal');schedule();});open('tutorialModal');}
function review(){cancelAI();document.querySelectorAll('.modal-overlay.active').forEach(el=>close(el.id));reviewAt=history.length-1;$('reviewSlider').max=history.length-1;$('reviewOverlay').classList.add('active');showReview(reviewAt);}
function showReview(n){reviewAt=Math.max(0,Math.min(history.length-1,+n));const s=history[reviewAt];drawBoard($('reviewBoard'),s);$('reviewSlider').value=reviewAt;$('reviewMoveNum').textContent='第 '+reviewAt+' 手';$('reviewMoveNotation').textContent=reviewAt?note(events[reviewAt-1]):'初始局面';const a=E.score(s);$('reviewMoveEval').textContent=`黑 ${a.black} : 白 ${a.white}`;$('reviewMoveList').innerHTML=events.map((e,i)=>`<button class="parity-review-row ${reviewAt===i+1?'active':''}" data-move="${i+1}">${i+1}. ${escape(note(e))}</button>`).join('');$('reviewMoveList').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>showReview(b.dataset.move));const values=history.map(t=>{const sc=E.score(t);return 75-(sc.white-sc.black)/36*65;});$('reviewChartLine').setAttribute('d',values.map((v,i)=>`${i?'L':'M'}${30+i*365/Math.max(values.length-1,1)},${v}`).join(' '));$('reviewResult').textContent=state.over?name(state.winner)+(state.winner==='draw'?'':'胜'):'对局进行中';}
function endReview(){reviewAt=null;$('reviewOverlay').classList.remove('active');schedule();}
function record(){return {format:'bio-go',version:3,state,history,events};}
function importRecord(r){if(!['bio-go','parity-go'].includes(r?.format)||r.version!==3||!Array.isArray(r.history)||!r.history.length||r.history.length>10001||!r.history.every(s=>s?.bioMode&&s.bio?.simple&&E.valid(s))||!Array.isArray(r.events)||r.events.length!==r.history.length-1||!r.state?.bioMode||!r.state.bio?.simple||!E.valid(r.state))throw new Error('不是有效的生物棋 v3 棋谱');if(JSON.stringify(r.state)!==JSON.stringify(r.history.at(-1)))throw new Error('棋谱末局与最终状态不一致');r.events.forEach(e=>{if(!e||!['black','white'].includes(e.color)||!(e.point===null||Number.isInteger(e.point)&&e.point>=0&&e.point<36)||!Array.isArray(e.destinations)||e.destinations.some(i=>!Number.isInteger(i)||i<0||i>35))throw new Error('棋谱事件格式错误');});cancelAI();state=E.copy(r.state);history=E.copy(r.history);events=E.copy(r.events);version++;mode='local';render();}
function exportPanel(){const text=JSON.stringify(record(),null,2);$('pgnModalContent').innerHTML='<h3>导出生物棋棋谱</h3><p>完整保存迁移落点、颜色锁、随机种子和每手局面。</p><textarea class="pgn-textarea" id="recordText" readonly></textarea><button class="choice-btn" id="saveRecord">下载 .json</button><button class="choice-btn" id="copyRecord">复制</button>';$('recordText').value=text;on('saveRecord',()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=u;a.download='生物棋-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});on('copyRecord',()=>copyText(text));open('pgnModal');}
function importPanel(){if(mode==='online')return message('请先断开联机再导入棋谱。');$('pgnModalContent').innerHTML='<h3>导入生物棋棋谱</h3><input id="recordFile" type="file" accept=".json"><textarea class="pgn-textarea" id="recordText" placeholder="粘贴导出的 JSON 棋谱"></textarea><button class="choice-btn" id="loadRecord">导入</button><p id="recordError"></p>';on('loadRecord',()=>{try{importRecord(JSON.parse($('recordText').value));close('pgnModal');}catch(e){$('recordError').textContent=e.message;}});$('recordFile').onchange=async e=>{const f=e.target.files[0];if(f&&f.size<5000000)$('recordText').value=await f.text();};open('pgnModal');}
async function copyText(t){try{await navigator.clipboard.writeText(t);message('已复制');}catch{modal('复制内容','<textarea id="copyFallback" class="pgn-textarea" readonly></textarea>');$('copyFallback').value=t;$('copyFallback').select();}}
function onlineUI(){const r=room;$('onlineStatusText').textContent=r?(r.connected?'已连接 · '+r.roomCode+' · '+name(r.localColor):(r.error||'正在连接房间服务器…')):'未连接';$('onlineDot').className='online-dot '+(r?.connected?'on':'off');$('peerDot').style.display=r?'':'none';$('peerStatusText').style.display=r?'':'none';$('peerStatusText').textContent=r?((r._peerOnline&&joined)?'对手已就绪':'等待对手') :'';$('peerDot').className='online-dot '+(r?._peerOnline?'on':'off');$('btnDisconnect').style.display=r?'block':'none';}
function sendState(){room?.send({type:'state',version,record:record()});}
function requestRemote(kind){if(!joined)return message('对手尚未就绪。');requested={kind,version};room.send({type:'request',kind,version});message('已请求对方同意'+({undo:'悔棋',reset:'重开',draw:'和棋'})[kind]);}
function acceptOperation(kind){if(kind==='undo')undo(true);if(kind==='reset')reset(true);if(kind==='draw'){state=E.copy(state);E.finish(state,'双方同意和棋','draw');history[history.length-1]=E.copy(state);version++;render();victory();}sendState();}
function receive(msg){if(!room)return;if(msg.type==='hello'&&room.isHost){if(peerId&&peerId!==msg._sender)return;peerId=msg._sender;joined=true;sendState();onlineUI();return;}if(peerId&&peerId!==msg._sender)return;if(msg.type==='state'&&!room.isHost&&Number.isInteger(msg.version)&&msg.version>=version){try{const m=mode;importRecord(msg.record);mode=m;version=msg.version;peerId=msg._sender;joined=true;render();onlineUI();if(state.over)victory();}catch{message('收到无效局面，未应用。');}return;}if(msg.type==='action'&&room.isHost&&joined&&msg.version===version&&state.turn==='white')commit(msg.point);if(msg.type==='request'&&msg.version===version&&['undo','reset','draw'].includes(msg.kind)){if(confirm('对方请求'+({undo:'悔棋',reset:'重开',draw:'和棋'})[msg.kind]+'，是否同意？')){if(room.isHost)acceptOperation(msg.kind);else room.send({type:'accept',kind:msg.kind,version});}}if(msg.type==='accept'&&room.isHost&&msg.version===version&&requested?.kind===msg.kind&&requested.version===version){requested=null;acceptOperation(msg.kind);}if(msg.type==='resign'&&room.isHost){state=E.copy(state);E.finish(state,'白方认输','black');history[history.length-1]=E.copy(state);version++;sendState();render();victory();}if(msg.type==='goodbye'){joined=false;room._peerOnline=false;onlineUI();}}
function disconnect(){room?.disconnect();room=null;peerId=null;joined=false;mode='local';onlineUI();render();}
function connect(host){if(location.protocol==='file:'&&(!host&&$('joinRoomInput').value.startsWith('3')))return message('局域网房间请从房主提供的 http:// 地址打开游戏后再加入。');cancelAI();room?.disconnect();mode='online';clockActive=false;room=new ParityOnline(window.game);window.game.onlineBrokerIndex=+$('onlineBroker').value;peerId=null;joined=false;version=0;if(host){reset(true);version=0;$('hostRoomCode').textContent=room.hostGame();}else if(!room.joinGame($('joinRoomInput').value)){disconnect();return message('请输入七位房间码。');}onlineUI();render();}
window.game={updateUI:render,undo:()=>undo(),resetGame:()=>{if(confirm('重新开始当前对局？'))reset();},proposeDraw:()=>{if(mode==='online')requestRemote('draw');else if(confirm('双方同意和棋？')){E.finish(state,'双方同意和棋','draw');history[history.length-1]=E.copy(state);render();victory();}},copyNotation:()=>copyText(events.map((e,i)=>`${i+1}. ${note(e)}`).join('\n')),addLog:message,_t:k=>({peerJoined:'对手加入',peerLeft:'对手断开'})[k]||k,_refreshOnlineUI:onlineUI,_onOnlineConnected:()=>{onlineUI();if(!room.isHost)room.send({type:'hello'});},_onOnlineDisconnected:()=>{joined=false;onlineUI();message('连接中断，正在重连；棋盘暂时锁定。');},_onRemoteMessage:receive};
// Diagnostics expose the same controller used by the UI, for regression checks.
window.ParityApp={getState:()=>E.copy(state),record:()=>E.copy(record()),reviewState:()=>reviewAt===null?null:{state:E.copy(history[reviewAt]),index:reviewAt},importRecord,action,commit,mode:()=>mode,reset:()=>reset(true)};
function boot(){
 $('sidePanelTitle').textContent='生物棋';document.title='生物棋 · 基线改造版';$('settingsRow').classList.remove('hidden');$('btnDraw').insertAdjacentHTML('beforebegin','<button class="btn-draw" id="btnPass">停一手</button>');$('sidePanelActions').insertAdjacentHTML('beforeend','<button class="btn-draw" id="btnResign">认输</button>');$('bondListContent').previousElementSibling.innerHTML='面积计分 <span class="collapse-arrow">▼</span>';
 ['btnNuclear','btnGiveElectron','bondDisplayOverlay','bondIndicatorOverlay','electronDonorOverlay','coordLabels','btnBoardSize','mBtnBoardSize','editRows','editCols','mEditRows','mEditCols'].forEach(id=>$(id)?.remove());$('editTools').innerHTML='<button class="edit-tool-btn" id="paintBlack">黑子</button><button class="edit-tool-btn" id="paintWhite">白子</button><button class="edit-tool-btn" id="paintEmpty">擦除</button><button class="edit-tool-btn" id="editTurn">切换先手</button><button class="edit-tool-btn" id="editDone">完成编辑</button>';
 on('paintBlack',()=>brush='black');on('paintWhite',()=>brush='white');on('paintEmpty',()=>brush='empty');on('editTurn',()=>{state.turn=E.other(state.turn);state.seen=[E.hash(state)];history=[E.copy(state)];render();});on('editDone',()=>{editing=false;document.body.classList.remove('debug-active');render();});
 on('btnDebug',()=>{if(mode==='online')return message('请先断开联机再编辑。');cancelAI();mode='local';editing=!editing;document.body.classList.toggle('debug-active',editing);render();});
 on('btnPass',()=>action(null));on('btnResign',()=>{if(state.over||!confirm('确认认输？'))return;const loser=mode==='online'?room.localColor:mode==='ai'?E.other(aiColor):state.turn;if(mode==='online'&&!room.isHost){room.send({type:'resign'});return;}E.finish(state,name(loser)+'认输',E.other(loser));history[history.length-1]=E.copy(state);version++;sendState();render();victory();});
 on('btnRules',rules);on('btnTutorial',()=>tutorial());on('btnFlip',()=>{flipped=!flipped;render();});on('btnCoords',()=>{coords=!coords;render();});on('btnAI',()=>setMode(mode==='ai'?'local':'ai'));on('btnAutoPlay',()=>setMode(mode==='auto'?'local':'auto'));on('btnAZDemo',()=>{levels={black:2,white:6};setMode('auto');});$('btnAZDemo').title='AI 演示：2 级对 6 级';
 document.querySelectorAll('.ai-diff-chip').forEach(b=>b.onclick=()=>{level=+b.dataset.lv;levels={black:level,white:level};render();schedule();});document.querySelectorAll('.ai-color-chip').forEach(b=>b.onclick=()=>{aiColor=b.dataset.color==='auto'?E.other(state.turn):b.dataset.color;render();schedule();});
 const opts=Array.from({length:6},(_,i)=>`<option value="${i+1}">${i+1} 级 · ${['随机','入门','普通','进阶','困难','专家'][i]}</option>`).join('');$('modelWhite').innerHTML=opts;$('modelBlack').innerHTML=opts;$('modelWhite').value=4;$('modelBlack').value=4;$('modelCfgTitle').textContent='AI 对弈配置';$('modelCfgNote').textContent='黑白双方可独立选择强度。级别越高，搜索时间与深度越大。随时点击自动对弈图标暂停，或者继续观看。';$('modelWhite').closest('.theme-section').querySelector('.theme-section-label').textContent='分别设置双方 AI';$('modelSims').closest('.model-cfg-row').remove();on('btnModelCfg',()=>open('modelCfgModal'));on('modelCfgClose',()=>{close('modelCfgModal');schedule();});const applyAI=()=>{levels={black:+$('modelBlack').value,white:+$('modelWhite').value};level=levels[aiColor];close('modelCfgModal');render();schedule();};on('modelCfgApply',applyAI);on('modelCfgStart',()=>{applyAI();setMode('auto');});
 on('btnNotation',()=>{$('notationSection').style.display=$('notationSection').style.display==='none'?'':'none';});$('notationSection').insertAdjacentHTML('beforeend','<button class="theme-btn" id="exportGame">导出棋谱</button><button class="theme-btn" id="importGame">导入棋谱</button>');on('exportGame',exportPanel);on('importGame',importPanel);on('mpgnExport',exportPanel);on('mpgnImport',importPanel);
 on('btnReview',review);on('reviewCloseBtn',endReview);on('reviewBtnClose',endReview);on('reviewBtnNewGame',()=>{endReview();reset();});on('reviewBtnFirst',()=>showReview(0));on('reviewBtnPrev',()=>showReview(reviewAt-1));on('reviewBtnNext',()=>showReview(reviewAt+1));on('reviewBtnLast',()=>showReview(history.length-1));$('reviewSlider').oninput=e=>showReview(e.target.value);['reviewProgress','reviewAccuracy','reviewClassSummary','reviewArrowToggles'].forEach(id=>$(id).style.display='none');document.querySelectorAll('#reviewOverlay .review-depth-row').forEach(e=>e.style.display='none');$('reviewChartLabel').textContent='面积差趋势（白方 − 黑方，非胜率）';$('reviewChartSvg').querySelectorAll('text').forEach((t,i)=>t.textContent=['+36','0','−36'][i]);
 on('btnOnline',()=>open('onlineModal'));$('joinRoomInput').maxLength=7;$('joinRoomInput').placeholder='如 2ABCDEF';$('onlinePanelHost').insertAdjacentHTML('afterbegin','<label>联机服务器 <select id="onlineBroker"><option value="3">局域网房间服务</option><option value="2">公共服务器 C</option><option value="0">公共服务器 A</option><option value="1">公共服务器 B</option></select></label>');on('onlineTabHost',()=>onlineTab('host'));on('onlineTabJoin',()=>onlineTab('join'));$('onlineBroker').value=location.protocol==='file:'?'2':'3';$('onlineBroker').querySelector('[value="3"]').disabled=location.protocol==='file:';on('btnCreateGame',()=>connect(true));on('btnJoinGame',()=>connect(false));on('btnCopyRoom',()=>copyText($('hostRoomCode').textContent));on('btnDisconnect',disconnect);
 on('btnClock',()=>{$('timerSection').style.display=$('timerSection').style.display==='none'?'':'none';});on('btnClockSet',()=>{if(mode==='online')return message('联机对局暂使用不限时。');clockTime={black:+$('clockNumInput').value*60000,white:+$('clockNumInput').value*60000};increment=+$('clockIncInput').value*1000;clockActive=false;clockRender();});on('btnClockToggle',()=>{if(mode==='online')return message('联机对局暂使用不限时。');if(!state.over&&clockTime.black>0&&clockTime.white>0)clockActive=!clockActive;lastTick=performance.now();});[['clockSlider','clockNumInput'],['clockIncSlider','clockIncInput']].forEach(([a,b])=>{ $(a).oninput=()=>$(b).value=$(a).value;$(b).oninput=()=>$(a).value=$(b).value;});document.querySelectorAll('.clock-preset-chip').forEach(b=>b.onclick=()=>{$('clockNumInput').value=$('clockSlider').value=b.dataset.min;$('clockIncInput').value=$('clockIncSlider').value=b.dataset.inc;$('btnClockSet').click();});
 on('btnSidebar',()=>toggleSidebar());on('sidebarMobileToggle',()=>toggleSidebar(false));on('btnSettingsToggle',()=>$('settingsRow').classList.toggle('hidden'));
 $('btnElements').title='棋块与气孔查询';on('btnElements',()=>{const seen=new Set(),rows=[];for(let i=0;i<36;i++)if(state.board[i]&&!seen.has(i)){const g=E.group(state.board,i);g.forEach(j=>seen.add(j));rows.push(`<p>${name(state.board[i].color)} ${g.map(E.coord).join('、')}<br>气：${E.libs(state.board,g).map(E.coord).join('、')||'无'}</p>`);}modal('棋块与气孔查询',rows.join('')||'<p>尚未落子。</p>');});
 $('btnLang').style.display='';
 $('settingsMobileRow').innerHTML='';document.querySelectorAll('#settingsRow > .settings-icon-btn').forEach(source=>{const b=source.cloneNode(true);b.removeAttribute('id');b.onclick=()=>source.click();$('settingsMobileRow').append(b);});
 try{if(localStorage.getItem('bio_go_sidebar_hidden')==='1')toggleSidebar(true);}catch{}document.querySelectorAll('.collapsible-header').forEach(h=>h.onclick=()=>{h.classList.toggle('collapsed');$(h.dataset.target)?.classList.toggle('collapsed');});document.querySelectorAll('.modal-overlay').forEach(el=>el.addEventListener('click',e=>{if(e.target===el){close(el.id);schedule();}}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal-overlay.active').forEach(el=>close(el.id));endReview();}if(reviewAt!==null&&e.key==='ArrowLeft')showReview(reviewAt-1);if(reviewAt!==null&&e.key==='ArrowRight')showReview(reviewAt+1);});
 const labels={tcWhiteCell:'棋盘底色',tcBlackCell:'棋盘线色',tcDotWhite:'白子标记',tcDotBlack:'黑子标记'};Object.entries(labels).forEach(([id,t])=>{const p=$(id).parentElement;const l=p.querySelector('label')||p.querySelector('.theme-color-label');if(l)l.textContent=t;});$('themeLabelDots')&&($('themeLabelDots').textContent='迁移标记');document.querySelectorAll('.theme-preview-piece').forEach(e=>e.textContent='↻');
 const modalObserver=new MutationObserver(()=>{if(document.querySelector('.modal-overlay.active'))cancelAI();else schedule();});document.querySelectorAll('.modal-overlay').forEach(el=>modalObserver.observe(el,{attributes:true,attributeFilter:['class']}));
 render();message('欢迎来到生物棋。点击交叉点落子，工具栏查看规则与教学。');
 setInterval(()=>{const now=performance.now(),dt=now-lastTick;lastTick=now;if(clockActive&&!state.over&&reviewAt===null&&!document.querySelector('.modal-overlay.active')){clockTime[state.turn]=Math.max(0,clockTime[state.turn]-dt);if(!clockTime[state.turn]){E.finish(state,name(state.turn)+'超时',E.other(state.turn));history[history.length-1]=E.copy(state);render();victory();}}clockRender();if(room?.connected&&!room.isHost&&!joined)room.send({type:'hello'});},500);
}
function onlineTab(t){['host','join'].forEach(x=>{$('onlineTab'+(x==='host'?'Host':'Join')).classList.toggle('active',x===t);$('onlinePanel'+(x==='host'?'Host':'Join')).classList.toggle('active',x===t);});}
function clockRender(){for(const c of ['black','white']){const n=Math.ceil(clockTime[c]/1000);$('clock'+(c==='black'?'Black':'White')).textContent=(c==='black'?'黑 ':'白 ')+Math.floor(n/60)+':'+String(n%60).padStart(2,'0');}$('btnClockToggle').textContent=clockActive?'暂停':'开始';}
window.addEventListener('DOMContentLoaded',boot);
})();
